<?PHP
if( SETUP::$System['SearchWithLike'] && preg_match('/^(cR|bR|mR)$/u', $_Mode) ){
if( !isset($_SearchNotLike) ){
$_SearchNotLike = [];
}else if( gettype($_SearchNotLike)=="string" ){
$_SearchNotLike = explode(',', eNsp($_SearchNotLike));
}
for($n=0; $n<count($_Form); $n++){
if( $_Form[$n][3]=="T" && !preg_match('/^(F4|P4|CDI|\+|\-|\+,|\-,|C|\*)$/u', $_Form[$n][2]) && substr($_Form[$n][1],0,3)!="cd_" ){
if( $_POST[$_Form[$n][1]]!="" && mb_strlen($_POST[$_Form[$n][1]])<$_Form[$n][4] && !preg_match('/^(<|>|=)/u', $_POST[$_Form[$n][1]][0]) ){
if( !isset($_POST["_INPUT_".$_Form[$n][1]]) && !in_array($_Form[$n][1], $_SearchNotLike) ){
if( $_POST[$_Form[$n][1]][0]!="*" ) $_POST[$_Form[$n][1]] = "*".$_POST[$_Form[$n][1]];
if( mb_substr($_POST[$_Form[$n][1]],-1)!="*" ) $_POST[$_Form[$n][1]] = $_POST[$_Form[$n][1]]."*";
}
}
}
}
}
if( !isset($_MSGTIME[0]) || $_MSGTIME[0]=='' ) $_MSGTIME[0] = 1000;
if( $_MSGTIME[0]<100 ) $_MSGTIME[0] = (float)$_MSGTIME[0]*1000;
if( !isset($_MSGTIME[1]) || $_MSGTIME[1]=='' ) $_MSGTIME[1] = 2000;
if( $_MSGTIME[1]<100 ) $_MSGTIME[1] = (float)$_MSGTIME[1]*1000;
$_NotInTemporary = "";
foreach($_POST as $k=>$v){
if( mb_substr($k,0,8)=="_FILTER_" && isset($_POST[mb_substr($k,8)]) ){
$inOut = "in";
$newValor = "";
$v = str_replace(
array(".", "&#13;", "&#10;"),
array("&#46;", CHR13, CHR10),
$v
);
$dim = explode(CHR13, str_replace(",", CHR13, $v));
for( $n=0; $n<count($dim); $n++ ){
$txt = trim($dim[$n]);
if( $txt<>"" ){
if( $txt=="<>" ){
$inOut = "out";
continue;
}else if( $txt=="!=" ){
$inOut = "list";
if( SS::isDriver('mysql,mysqli') ){
DB::query( 'CREATE TEMPORARY TABLE _seek (
valor varchar(120) NOT NULL
)' );
}else if( SS::isDriver("informix") ){
DB::query( 'CREATE TEMP TABLE _seek (
valor varchar(120) NOT NULL
)' );
}else if( DB::isDriver("oci") ){
DB::query( 'DECLARE LOCAL TEMPORARY TABLE _seek (
valor varchar(120) NOT NULL
)' );
}
$_POST[mb_substr($k,8)] = "";
$_NotInTemporary = mb_substr($k,8);
continue;
}
if( $inOut=="list" ){
DB::query("insert into _seek (valor) values ('{$txt}')");
}else{
$tipo = $_pField[mb_substr($k,8)][2];
if( preg_match('/^(\-|\+)$/u', $tipo) ){
$txt = str_replace(".", "", $txt);
}else if( preg_match('/^(\-\,|\+\,)$/u', $tipo) ){
$txt = str_replace(array(".",","), array("","."), $txt);
}else if( preg_match('/^(F4|P4|CDI)$/u', $tipo) ){
$txt = eDataFormat($txt, $tipo, "d");
}
if( $newValor<>"" ) $newValor .= ",";
$newValor .= "'{$txt}'";
}
}
}
if( trim($newValor)<>"" ){
if( $inOut=="in" ){
$_POST[mb_substr($k,8)] = "({$newValor})";
$_POST[$k] = $_ENV['ON'];
}else if( $inOut=="out" ){
$_POST[mb_substr($k,8)] = "){$newValor}(";
$_POST[$k] = $_ENV['ON'];
}
}
}
}
if(
$Opcion=='M'  || $Opcion=='A'  || $Opcion=='B' ||
$Opcion=='mR' || $Opcion=='cR' || $Opcion=='bR'
){
include_once(DIREDES."sanitizar.inc");
}
if( $_DBADDFILTER[0]=='=' ){
$_DBADDFILTEREXTRA = mb_substr($_DBADDFILTER,1);
if( mb_substr($_DBADDFILTEREXTRA,-1)==')' || mb_substr($_DBADDFILTEREXTRA,-1)==';' ){
list( $NomFunc ) = explode('(',$_DBADDFILTEREXTRA);
if( function_exists($NomFunc) ){
if( $GLOBALS['_DEBUG']==14 ) eTron('eval: '.'return '.$_DBADDFILTEREXTRA.';');
$_DBADDFILTEREXTRA = eval('return '.$_DBADDFILTEREXTRA.';');
}
}
$_DBADDFILTER = '';
}
include_once($Dir_.'condicion.inc');
if( isset($_POST) ){
if( $_POST['_SAVEDATALIST']!='' ) $_SAVEDATALIST = $_POST['_SAVEDATALIST'];
}else if( $_POST['_SAVEDATALIST']!='' ) $_SAVEDATALIST = $_POST['_SAVEDATALIST'];
$tmpAutoMenu = ( isset($_GET['_STOP']) ) ? 'eAutoMenu(0);':'';
$Busca = '';
$aBusca = '';
$_Grabar = '';
$NTX = '';
$NTX2 = '';
$_WHERE = &$NTX;
$TotalHojas = count($DFichero);
$MenosHojas = 0;
$Tablas = '';
$_DBTABLE = '#';
$sAlias = '';
$_TipoVar = array();
$_TableUnique = array();
$DimIndice2 = explode(',', $_DBINDEX2);
$DimIndice3 = explode(',', $_DBINDEX3);
for($nc=0; $nc<$TotalHojas; $nc++){
$DimTabla[$nc] = '';
if( $DFichero[$nc][0]=='=' || $DFichero[$nc][0]=='>' ){
$MenosHojas++;
continue;
}
if( $DFichero[$nc][0]=='-' ){
$FicheroD = eScript(trim(mb_substr($DFichero[$nc], 1)));
}else{
$FicheroD = eScript(str_replace('*','',$DFichero[$nc]));
}
$OnCampos = false;
$n = 0;
$sBuffer = '';
$ElPuntoEsRem = true;
$_DimEDF = @OpenDF($FicheroD,0);
for($nDimFCH=0; $nDimFCH<count($_DimEDF); $nDimFCH++){
$buffer = trim($_DimEDF[$nDimFCH]);
$sBuffer = $buffer;
if( !@LeeDF($buffer, $DimOpcion, $_Variable, $SaltarLinea, $_Form, $Chr_1, $_FIELDSET, $_TmpFieldSet, $_EnLinea, $_TmpEnLinea, $_EnColumna, $_TmpEnColumna, $TipoEntrada, $ElPuntoEsRem, $next_Line) ){
if( $Chr_1=='[' ) $TipoEntrada = '#';
continue;
}
if( $Chr_1=='[' && mb_substr($buffer,-1)=="|" && !preg_match('/^\[FIELDS\]/iu',$buffer) ) _addBuffer($buffer, $nDimFCH, $_DimEDF);
$ElPuntoEsRem = true;
if( mb_substr($buffer,0,2)==REM ) continue;
if( mb_strpos($buffer, REM)!==false ){
if( eSubstrCount(mb_strtoupper($buffer), '[UPLOADFILE]')==0 ){
$p = mb_strpos($buffer, REM);
if( mb_substr($buffer,$p-1,1)!='\\' ){
if( eSubstrCount(mb_chr(39).'":', mb_substr($buffer, $p-1, 1))==0 ) $buffer = chop(mb_substr($buffer, 0, $p));
}
}
}
if( mb_ord($buffer[0])==91 ){
_AtomizaLabel($Opcion, $buffer, $Etiqueta, $bufferData, $tmp, $OkModo, $TipoEntrada, $JsHtm, $Comando);
switch( $Etiqueta ){
case 'FIELDS':
$OnCampos = true;
break;
case 'DBTABLE':
$tmpBuffer = trim($_DimEDF[$nDimFCH+1]);
if( $tmpBuffer[0]=='¿' ){
if( eSubstrCount(mb_strtoupper($tmpBuffer), '[DBTABLE]')>0 ){
$ElPuntoEsRem = true;
if( @LeeDF($tmpBuffer, $DimOpcion, $_Variable, $SaltarLinea, $_Form, $Chr_1, $_FIELDSET, $_TmpFieldSet, $_EnLinea, $_TmpEnLinea, $_EnColumna, $_TmpEnColumna, $TipoEntrada, $ElPuntoEsRem, $next_Line) ){
continue;
}
}
}
list(, $DimTabla[$nc]) = explode(']', $buffer);
list($DimTabla[$nc]) = explode('|', $DimTabla[$nc]);
$DimTabla[$nc] = trim($DimTabla[$nc]);
$DimTabla[$nc] = _InVar($DimTabla[$nc]);
$_TableUnique[$DimTabla[$nc]] = 1;
if( $Tablas!='' ) $Tablas .= ',  ';
$Tablas .= $DimTabla[$nc].' '.mb_chr(65+$nc);
if( $DFichero[$nc][0]!='-' && $nc==0 ){
$_DBTABLE = $DimTabla[$nc];
$sAlias = mb_chr(65+$nc);
}
$n++;
if( $OnCampos ) $n++;
$OnCampos = false;
break;
case 'DBINDEX':
$tmpBuffer = trim($_DimEDF[$nDimFCH+1]);
if( $tmpBuffer[0]=='¿' ){
if( eSubstrCount( mb_strtoupper($tmpBuffer), '[DBINDEX]' ) > 0 ){
$ElPuntoEsRem = true;
if( @LeeDF( $tmpBuffer, $DimOpcion, $_Variable, $SaltarLinea, $_Form, $Chr_1, $_FIELDSET, $_TmpFieldSet, $_EnLinea, $_TmpEnLinea, $_EnColumna, $_TmpEnColumna, $TipoEntrada, $ElPuntoEsRem, $next_Line ) ){
continue;
}
}
}
list( , $DimIndice[$nc] ) = explode( ']', $buffer );
if( eSubstrCount( $DimIndice[$nc], ';' ) > 0 ){
list( $DimIndice[$nc] ) = explode( ';', $DimIndice[$nc] );
}
$DimIndice[$nc] = trim( $DimIndice[$nc] );
$n++;
if( $OnCampos ) $n++;
$OnCampos = false;
break;
case 'DBRANGE':
if( isset($__INSERTTOSEEK) && count($__INSERTTOSEEK)>0 ){
$d = explode('|', $buffer);
for($i=0; $i<count($d); $i++ ) $d[$i] = trim($d[$i]);
if( $_POST[$d[2]]!="" || $_POST[$d[3]]!="" ){
$_ConDBRange[$d[1]] = true;
$condi = ((eSubstrCount(',TRUE,!FALSE,1,,', ','.mb_strtoupper($d[4]).',')==1)?"=":"");
$comilla = "'";
$lenDato = max(mb_strlen($_POST[$d[2]]), mb_strlen($_POST[$d[3]]));
if( $_POST[$d[2]]!="" && $_POST[$d[3]]!="" && $_POST[$d[2]]>$_POST[$d[3]] ){
list($_POST[$d[2]], $_POST[$d[3]]) = array($_POST[$d[3]], $_POST[$d[2]]);
}
if( $_POST[$d[2]]!="" && $_POST[$d[3]]!="" ){
$_POST[$d[1]] = ">{$condi}#2{$comilla} and {$d[1]}<{$condi}{$comilla}#3";
}else if( $_POST[$d[2]]!="" ){
$_POST[$d[1]] = ">{$condi}#2";
}else if( $_POST[$d[3]]!="" ){
$_POST[$d[1]] = "<{$condi}#3";
}
if( $lenDato==10 ){
if( SS::isDriver('oracle', 'informix') ){
if( $_POST[$d[2]]!="" ) $_POST[$d[2]] = eYmd2Dmy($_POST[$d[2]]);
if( $_POST[$d[3]]!="" ) $_POST[$d[3]] = eYmd2Dmy($_POST[$d[3]]);
}
}
$_POST[$d[1]] = str_replace( array("#2","#3"), array($_POST[$d[2]],$_POST[$d[3]]), $_POST[$d[1]]);
}
}
break;
case 'NOTE':
break 2;
default:
if( $OnCampos ) $n++;
$OnCampos = false;
}
}else{
if( $OnCampos && eSubstrCount($buffer, '|')>7 ){
$tmp = explode('|', $buffer);
$_TipoVar[trim($tmp[1])] = trim($tmp[2]);
}else{
if(	$buffer[0]=="{" ){
$tmp = explode('|', $buffer);
$tmp2 = explode('}', mb_strtoupper(str_replace(" ","",mb_substr($tmp[0],1))));
if( $tmp2[0]=="SLMENU" && eSubstrCount($tmp2[1],"A")==1 && mb_strtoupper(str_replace(" ","",$tmp[4]))=="FORMSTATIC" ){
if( $Opcion=='M' || $Opcion=='A' || $Opcion=='B' ){
_RecuperaFileSetup($tmp[2]);
}
}
}
}
}
}
unset($_DimEDF);
if( $DimTabla[$nc]=='' ) $MenosHojas++;
$DimGrabar[$nc] = '';
$DimInsert[$nc] = '';
$DimLong[$nc] = 0;
}
for( $nc=count($DimTabla)-1; $nc>=0; $nc-- ){
if( $DimTabla[$nc]=='' ){
array_splice($DFichero, $nc, 1);
array_splice($DimTabla, $nc, 1);
array_splice($DimIndice, $nc, 1);
array_splice($DimIndice2, $nc, 1);
array_splice($DimGrabar, $nc, 1);
array_splice($DimInsert, $nc, 1);
array_splice($DimLong, $nc, 1);
}
}
$TotalHojas -= $MenosHojas;
if( eSubstrCount($_DBADDFILTER, '{')>0 && eSubstrCount($_DBADDFILTER, '}')>0 ){
if( $GLOBALS['_DEBUG']==14 ) eTron('eval: '.'return '.$_DBADDFILTER.';');
$_DBADDFILTER = eval('return "'.$_DBADDFILTER.'";');
}else if( (eSubstrCount($_DBADDFILTER, '()')==1 || eSubstrCount($_DBADDFILTER, '( )')==1) && eSubstrCount($_DBADDFILTER, 'now()')==0 ){
if( $GLOBALS['_DEBUG']==14 ) eTron('eval: '.'return '.$_DBADDFILTER.';');
$_DBADDFILTER = eval('return '.$_DBADDFILTER.';');
}
if( eSubstrCount($Opcion,'R')>0 ){
if( $_SERVER["REQUEST_METHOD"]!='POST' ){
$VarInicial = 1;
$EsCampoFiltro = false;
$n=-1;
foreach($_GET as $c=>$vv){
$n++;
$Dim[$n] = $c."='".$vv."'";
if( $c=='_NOBUTTON' || $c=='_FORMBUTTONS' || $c=='_STOP' || $c=='_CLOSE_' || $c=='_PSOURCE' || $c=='_WSList' ) continue;
if( mb_substr($c,0,3)=='___' ) continue;
foreach($_SESSION["CHECK"] as $k3=>$v3){
if( $c==$k3 && isset($_SESSION[$v3]) && $vv<>$_SESSION[$v3] ){
$error = "Operación no permitida";
if( $_SESSION["_D_"]!='' ) $error = "3: Valor de variable de sesión no permitida: {$k3}<>".$_SESSION[$v3];
eMessage( $error, 'HSE' );
}
}
if( $EsCampoFiltro ){
if( ($vv[0]=='"' || $vv[0]=="'") && $vv[0]==mb_substr($vv,-1) ){
$vv = mb_substr($vv,1,-1);
}
${$c} = $vv;
if( trim($Dim[$n])<>"" && $Dim[$n][0]!='_' ){
if( $Busca!='' ) $Busca .= ' and ';
$Busca .= $Dim[$n];
if( $aBusca!='' ) $aBusca .= ' and ';
$aBusca .= 'A.'.$Dim[$n];
}
}else if( $c=='_SEEK' ) $EsCampoFiltro = true;
}
$NTX = $Busca;
}else{
$Grabar = $Busca = $aBusca = $NTX = '';
$dBusca = '';
$DimNomVar  = array_keys($_POST);
$DimValor   = array_values($_POST);
$VarInicial = 0;
if( $_FILTER!='' ){
$tmp = urldecode($_FILTER);
$tmp = str_replace(' like ', '=' ,$tmp );
$tmp = str_replace("\\'", "'" , $tmp );
$tmp = str_replace('%', '*' , $tmp );
$tmp = explode(' and ', $tmp);
for($n=0; $n<count($tmp); $n++){
$tmp[$n] = trim($tmp[$n]);
if( mb_substr($tmp[$n],0,2)=='A.' ) $tmp[$n] = mb_substr($tmp[$n], 2);
$sTmp = explode( '=', $tmp[$n] );
$sTmp[0] = trim($sTmp[0]);
$sTmp[1] = trim($sTmp[1]);
if( $sTmp[1][0] == "'" || $sTmp[1][0] == '"' ) $sTmp[1] = mb_substr( $sTmp[1], 1, -1 );
array_push( $DimNomVar, $sTmp[0] );
array_push( $DimValor, $sTmp[1] );
}
}
for($n=0; $n<count($DimNomVar); $n++){
$DimNomVar[$n] = trim($DimNomVar[$n]);
$DimValor[$n] = trim($DimValor[$n]);
if( $MemDBRange[$DimNomVar[$n]]=="" ){
$DimValor[$n] = str_replace('"','&quot;',$DimValor[$n]);
}else{
if( !(eSubstrCount($DimValor[$n],'"')==2 && mb_substr($DimValor[$n],-11,1)=='"' && eSubstrCount(mb_substr($DimValor[$n],11,2), '"')==1) ){
$DimValor[$n] = str_replace('"','&quot;',$DimValor[$n]);
}
}
foreach( $_SESSION["CHECK"] as $k=>$v ){
if( $DimNomVar[$n]==$k && isset($_SESSION[$v]) && $DimValor[$n]<>$_SESSION[$v] ){
$error = "Operación no permitida";
if( $_SESSION["_D_"]!='' ) $error = "4: Valor de variable de sesión no permitida: {$k}<>".$$_SESSION[$v];
eMessage( $error, 'HSE' );
}
}
if( $_ConDBRange[$DimNomVar[$n]] ) $DimValor[$n] = stripslashes( $DimValor[$n] );
if( mb_substr($DimNomVar[$n], 0, 1)=='_' ){
if( mb_strlen($_Grabar) > 0 ) $_Grabar .= ', ';
$_Grabar .= $DimNomVar[$n]. '="' .$DimValor[$n]. '" ';
continue;
}
if( $DimNomVar[$n]=='_PSOURCE' ) continue;
if( mb_substr($DimNomVar[$n],0,3) == '___' ) continue;
if( SS::isDriver('informix') ){
}else{
if( !DB::isDriver("oci") && mb_strlen($DimValor[$n])==10 && mb_substr($DimValor[$n],2,1)=='-' && mb_substr($DimValor[$n],5,1)=='-' ){
$DimValor[$n] = mb_substr($DimValor[$n],6,4).mb_substr($DimValor[$n],2,4).mb_substr($DimValor[$n],0,2);
}
}
if( ($Opcion=='A' || $Opcion=='M' ) && $DimValor[$n]=="" ) $DimValor[$n] = "NULL";
if( $DimNomVar[$n]!=$_DBSERIAL[1] ){
if( mb_strlen($Grabar)>0 ) $Grabar .= '|';
if( $DimValor[$n]=='NULL' ){
$Grabar .= $DimNomVar[$n].'='.rtrim($DimValor[$n]).' ';
}else if( preg_match('/(\+|\-)/u', $_pField[$DimNomVar[$n]][2][0]) ){
$Grabar .= $DimNomVar[$n].'='.$DimValor[$n].' ';
}else if( $_pField[$DimNomVar[$n]][2]=="F4" && rtrim($DimValor[$n])=="" ){
$Grabar .= $DimNomVar[$n].'=NULL ';
}else if( !DB::isDriver("oci") ){
$Grabar .= $DimNomVar[$n].'="'.rtrim($DimValor[$n]).'" ';
}else{
$Grabar .= $DimNomVar[$n]."='".str_replace("'", "''", rtrim($DimValor[$n]))."' ";
}
}
if( SS::isDriver('informix') ){
$DimValor[$n] = trim(stripslashes($DimValor[$n]));
}else{
if( DB::isDriver("oci") ){
$DimValor[$n] = trim(stripslashes($DimValor[$n]));
}else{
}
}
if( is_array($_POST[$DimNomVar[$n]]) ){
$iValor = '';
foreach($_POST[$DimNomVar[$n]] as $clave=>$val){
if( $iValor!='' ) $iValor .= '|';
$iValor .= $val;
}
$DimValor[$n] = $iValor;
$sBusca = CondiSQL($DimNomVar[$n].'[]', $DimValor[$n]);
}else{
if( DB::isDriver("oci") ){
$sBusca = CondiSQLOracle($DimNomVar[$n], $DimValor[$n]);
}else{
$sBusca = CondiSQL($DimNomVar[$n], $DimValor[$n]);
}
}
if( $sBusca!= '' ){
if( $Busca!='' ) $Busca .= ' and ';
$Busca .= $sBusca;
if( $aBusca!='' ) $aBusca .= ' and ';
$iiConDBRange = false;
if( count($DimDBRange)>0 ){
for( $ii=0; $ii<count($DimDBRange); $ii++ ){
if( $DimDBRange[$ii][0] == $DimNomVar[$n] ){
$iiConDBRange = true;
break;
}
}
}
$aBusca .= str_replace( $DimNomVar[$n], 'A.'.$DimNomVar[$n], $sBusca );
}
if( in_array($DimNomVar[$n], $DimIndice) ){
if( $NTX!='' ) $NTX .= ' and ';
$NTX .= $DimNomVar[$n]. '="' .$DimValor[$n]. '" ';
}
if( $_DBINDEX2!='' ){
if( in_array($DimNomVar[$n], $DimIndice2) ){
if( preg_replace('/[0 .]/', '', $DimValor[$n])=='' && eSubstrCount($_DBINDEX2,',')==0 ){
}else{
if( $NTX2!='' ) $NTX2 .= ' and ';
if( DB::isDriver("oci") ){
$NTX2 .= $DimNomVar[$n]. "='" .str_replace("'","''",$DimValor[$n])."' ";
}else{
$NTX2 .= $DimNomVar[$n]. '="' .$DimValor[$n]. '" ';
}
}
}
}
if( $_DBINDEX3!='' ){
if( in_array($DimNomVar[$n], $DimIndice3) ){
if( preg_replace('/[0 .]/', '', $DimValor[$n])=='' && eSubstrCount($_DBINDEX3,',')==0 ){
}else{
if( $NTX3!='' ) $NTX3 .= ' and ';
if( DB::isDriver("oci") ){
$NTX3 .= $DimNomVar[$n]. "='" .str_replace("'","''",$DimValor[$n])."' ";
}else{
$NTX3 .= $DimNomVar[$n]. '="' .$DimValor[$n]. '" ';
}
}
}
}
}
if( (eSubstrCount($Opcion,'R')>0 || eSubstrCount('ABM',$Opcion)>0) && $_DBADDFILTER!='' ){
if( mb_strlen($Busca)>0 ) $Busca .= ' and ';
$Busca .= $_DBADDFILTER;
if( mb_strlen($NTX)>0 ) $NTX .= ' and ';
$NTX .= $_DBADDFILTER;
}
if( $_DBMEMO[$DimNomVar[$n]] ){
if( SS::isDriver('informix') ){
$_MemoContenido[] = $DimValor[$n];
}else if( SS::isDriver("informix") ){
$_MemoContenido[] = ifx_create_blob(1, 0, $DimValor[$n]);
}
}
}
if( $_NotInTemporary<>"" ){
$NomFile = $DFichero[0];
$FicheroD = eScript($NomFile);
$_Accion = 'Ll:'.$NomFile;
unset($_AUX_, $_ORDEN_, $_DESTINO_);
include($Dir_.'_lista.gs');
eEnd();
}
if( $_DBSQL=='' ){
$where = _qBuscar($Busca,$_DBTABLE);
if( $where!="" && $_DBFILTERIN!="" ) $where .= " and ".(($HaySelect)?"A.":"").$_DBFILTERIN;
$_TReg = DB::count($_DBTABLE, $where);
}else{
$tmpSQL = GrabaTmp('g_dbsql', '$usuCursor=array();'."\n".$_DBSQL, $LenDoc);
include( $tmpSQL );
_ShowError($php_errormsg, $tmpSQL, $LenDoc);
unset($_DBSQL);
}
if( $_TReg==0 && count($_DELFILTER)>0 ){
unset($_PHPSESSION);
$_ConDelFilter = true;
$_DelFilterURL = str_replace('{Op}',$Opcion[0],$_DELFILTER[5]);
$ListOriFichero = 'G'.$Opcion.':'.$OriFichero;
$Busca .= ' ';
for( $n=0; $n<count($_DELFILTER[1]); $n++ ){
$_DELFILTER[1][$n] = trim($_DELFILTER[1][$n]);
$p = mb_strpos( $Busca, $_DELFILTER[1][$n].'=' );
$ConLike = mb_strpos( $Busca, $_DELFILTER[1][$n].' ' );
if( mb_strlen($ConLike) > 0 ){
$Busca = mb_substr( $Busca, 0, $ConLike ) . mb_substr( $Busca, mb_strpos( $Busca.' and ', ' and ', $ConLike+1 ) );
$_POST[ $_DELFILTER[1][$n] ] = '';
if( isset($_POST) ) $_POST[ $_DELFILTER[1][$n] ] = '';
}else if( mb_strlen($p) > 0 ){
$Busca = mb_substr( $Busca, 0, $p ) . mb_substr( $Busca, mb_strpos( $Busca.' and ', ' and ', $p+1 ) );
$_POST[ $_DELFILTER[1][$n] ] = '';
if( isset($_POST) ) $_POST[ $_DELFILTER[1][$n] ] = '';
}
}
while( eSubstrCount( $Busca, '  ' ) > 0 ) $Busca = str_replace( '  ', ' ', $Busca );
while( eSubstrCount( $Busca, ' and and ' ) > 0 ) $Busca = str_replace( ' and and ', ' and ', $Busca );
$Busca = str_replace( ' and and ', ' and ', $Busca );
$Busca = trim($Busca);
if( mb_substr( $Busca,-3 ) == 'and' ) $Busca = mb_substr( $Busca, 0, mb_strlen($Busca)-3 );
if( mb_substr( $Busca,0,4 ) == 'and ' ) $Busca = mb_substr( $Busca, 4 );
if( trim($Busca)!='' ){
$where = _qBuscar($Busca,$_DBTABLE);
if( $where!="" && $_DBFILTERIN!="" ) $where .= " and ".(($HaySelect)?"A.":"").$_DBFILTERIN;
$_TReg = DB::count($_DBTABLE, $where);
}
if( $_DELFILTER[4]!='' ) include( eScript($_DELFILTER[4]) );
if( $_TReg == 0 || ( $_TReg > 1 && mb_strtoupper($_DELFILTER[3])=='NOLIST' ) ){
eMessage( '~NRC', 'HS', $_MSGTIME[1], 'if(window.name=="IWORK")history.go(-1);', 'NR' );
}else{
if( !empty($_DBLIMIT ) && $_LimitOn == false && $_TReg > $_DBLIMIT ){
eMessage( '~LEA|'.$_TReg, 'HS', 5000, '' ,'LE' );
}
if( !empty($_DELFILTER) && eSubstrCount(mb_strtoupper($_DELFILTER[0]), '{OP}') > 0 ){
$_DELFILTER[0] = mb_substr($_DELFILTER[0],0,mb_strpos($_DELFILTER[0],'{')). $Opcion .mb_substr($_DELFILTER[0],mb_strpos($_DELFILTER[0],'}')+1);
}
$tmp = explode(':', $_DELFILTER[0]);
$NomFile = $Fichero = trim($tmp[1]);
$_Accion = $_DELFILTER[0];
$OriFichero = $Fichero;
$Fichero = eScript( $Fichero );
$FicheroD = $Fichero;
$NomFile = 'edes.php';
$_Accion = $_DELFILTER[0];
list( $Opcion, $Fichero ) = explode( ':', mb_substr($_Accion,1) );
$_CambiaURL_ = mb_substr($_Accion,0,mb_strpos($_Accion,':')).':'.$Fichero;
$__='{#}eDes{#}';
eInit();
if( $_TReg == 1 ){
switch( $_Accion[0] ){
case 'F': include( $Dir_.'_ficha.gs'  ); break;
case 'G': include( $Dir_.'_gficha.gs' ); break;
case 'L': include( $Dir_.'_lista.gs'  ); break;
case 'E':
$NomFile = mb_substr($_Accion,2);
if( eSubstrCount( $NomFile, '(' )==1 && eSubstrCount( $NomFile, ')' )==1 ){
if( mb_substr($NomFile,-1)!=';' ) $NomFile .= ';';
if( $GLOBALS['_DEBUG']==14 ) eTron('eval: '.$NomFile.';');
eval($NomFile.';');
}else{
include(eScript($NomFile));
}
break;
default:
eMessage("~O|{$_Accion}",'HE');
}
}else{
switch( $_Accion[0] ){
case 'F':
case 'G':
case 'L':
include($Dir_.'_lista.gs');
break;
case 'E':
$NomFile = mb_substr($_Accion,2);
if( eSubstrCount( $NomFile, '(' )==1 && eSubstrCount( $NomFile, ')' )==1 ){
if( mb_substr($NomFile,-1)!=';' ) $NomFile .= ';';
if( $GLOBALS['_DEBUG']==14 ) eTron('eval: '.$NomFile.';');
eval($NomFile.';');
}else{
include( eScript($NomFile) );
}
break;
default:
eMessage("~O|{$_Accion}",'HE');
}
}
eEnd();
}
}else if( $_TReg==1 ){
$where = _qBuscar($Busca, $_DBTABLE);
if( $where!="" && $_DBFILTERIN!="" ) $where .= " and ".(($HaySelect)?"A.":"").$_DBFILTERIN;
$sTReg = $_TReg;
if( !empty($where) ) $where = "where {$where}";
DB::query("select * from {$_DBTABLE} {$where}");
$Fila = DB::get();
$_vF = &$Fila;
foreach($_SESSION["CHECK"] as $k=>$v){
if( isset($_vF[$k]) && isset($_SESSION[$v]) && trim($_vF[$k])<>$_SESSION[$v] ){
eMessage( "NoValor: {$k}", 'HSE' );
}
}
foreach($_vF as $key=>$val){
if( isDate($val) ){
if( isZero($_vF[$key]) ) $_vF[$key] = '';
}
}
if( count($_OTHERDF)>0 ){
if( $GLOBALS['_DEBUG']==14 ) eTron('eval: '.'return '.$_OTHERDF[1].';');
if( @eval('return '.$_OTHERDF[1].';') ){
if( eSubstrCount( mb_strtoupper($_OTHERDF[0]), '{OP}' ) > 0 ){
$_OTHERDF[0] = mb_substr($_OTHERDF[0],0,mb_strpos($_OTHERDF[0],'{')). $Opcion .mb_substr($_OTHERDF[0],mb_strpos($_OTHERDF[0],'}')+1);
}
unset($NomFile);
$_Accion = $_OTHERDF[0];
if( eSubstrCount( $_Accion, '.' ) == 0 ) $_Accion .= '.edf';
eInit();
switch( $_Accion[0] ){
case 'F':
$_Accion = mb_substr($_Accion,1);
$__='{#}eDes{#}';
include( $Dir_.'_ficha.gs' );
break;
case 'G':
$_Accion = mb_substr($_Accion,1);
$__='{#}eDes{#}';
include( $Dir_.'_gficha.gs' );
break;
case 'L':
$_Accion = mb_substr($_Accion,1);
$__='{#}eDes{#}';
include($Dir_.'_lista.gs');
break;
default:
eMessage("~O|{$_Accion}",'HE');
}
eEnd();
}
}
$IndicePadre = $Fila[$_DBINDEX];
$_Relacion = $IndicePadre;
$_TReg = $sTReg;
}else if( !empty($_DBLIMIT) && $_LimitOn==false ){
if( $_TReg>$_DBLIMIT ){
eMessage('~LE|'.$_TReg, 'HS', 5000, '', 'LE');
}
}
if( $_TReg==-100 ){
$where2 = _qBuscar($dBusca,$DimTabla[1]);
if( $where2!="" && $_DBFILTERIN!="" ) $where2 .= " and ".(($HaySelect)?"A.":"").$_DBFILTERIN;
$_TReg = DB::count( $DimTabla[1], $where2 );
eEnd();
}
}
$_DELFILTER = array();
$xDimIndice = explode(',', $_DBINDEX);
$xValIndice = array();
$IndiceMultiple = $aBusca;
for($n=0; $n<count($xDimIndice); $n++){
$xDimIndice[$n] = trim($xDimIndice[$n]);
if( isset($_POST[$xDimIndice[$n]]) ) $_vF[$xDimIndice[$n]] = $_POST[$xDimIndice[$n]];
if( $_vF[$xDimIndice[$n]]!='' && eSubstrCount( $IndiceMultiple,$xDimIndice[$n])==0 ){
if( $IndiceMultiple!='' ) $IndiceMultiple .= ' and ';
if( eSubstrCount( $xDimIndice[$n], '.' ) > 0 ){
$IndiceMultiple .= $xDimIndice[$n]."='".$_vF[$xDimIndice[$n]]."'";
}else{
$IndiceMultiple .= 'A.'.$xDimIndice[$n]."='".$_vF[$xDimIndice[$n]]."'";
}
}
}
if( $Opcion=='bR' || $Opcion=='cR' || $Opcion=='mR' ){
if( isset($__INSERTTOSEEK) ){
$_SAVEDATALIST = "";
$_FIELDSLIST = str_replace(
array(",_SAVEDATALIST", "||", "|", ",,"),
array(""			  ,  "" , "" , "," ),
$_FIELDSLIST
);
}
if( $_TReg==1 && $_SUBLISTADO_!=1 ){
if( $_DBRLOCK && $Opcion!='cR' ){
$xxTabla = array();
foreach($_TableUnique as $k=>$v) $xxTabla[] = $k;
$_DBRLOCK = DB::getHashRecord($xxTabla, $_DBINDEX."='".$IndicePadre."'");
}
Estadistica('gFi', 0, '', $_DBTABLE);
$Buscar = "{$DimTabla[0]} A";
for($nc=1; $nc<$TotalHojas; $nc++){
if( !empty($DimTabla[$nc]) ){
$Buscar .= ' left join '.$DimTabla[$nc].' '.mb_chr(65+$nc).' on ';
for( $i=0; $i<count($xDimIndice); $i++ ){
if( $i>0 ) $Buscar .= ' and ';
$Buscar .= mb_chr(65+$nc).'.'.$xDimIndice[$i] .'=A.'.$xDimIndice[$i].' ';
}
}
}
if( $_DBADDFILTER!='' ){
if( trim($IndiceMultiple)!='' && $_DBADDFILTER!='' ) $IndiceMultiple .= ' and ';
$IndiceMultiple .= $_DBADDFILTER;
}
$TCampos = ExtraeCampos();
$_PKSeek = _qBuscar($IndiceMultiple,$Buscar);
$where2 = _qBuscar($dBusca,$DimTabla[1]);
if( $where2!="" && $_DBFILTERIN!="" ) $_PKSeek .= " and ".(($HaySelect)?"A.":"").$_DBFILTERIN;
if( !empty($_PKSeek) ){
$_PKSeek = " where {$_PKSeek}";
}
DB::query("select {$TCampos} from {$Buscar} {$_PKSeek}");
$_Fila = DB::get();
$_LOGANSWER["form"] = $_Fila;
$_vF = &$_Fila;
_gsLastInsert($NTX);
foreach($_PHPSESSION as $k=>$v){
if( $_vF[$k]<>$v ) eMessage((($_PHPSESSIONMSG=='')?"(G{$Opcion}) Error de Sessión":$_PHPSESSIONMSG),'HSE');
}
foreach($_vF as $key=>$val){
if( isDate($val) ){
if( isZero($_vF[$key]) ) $_vF[$key] = '';
}
}
}elseif( $_TReg==0 ){
eMessage('~NRC', 'HS', $_MSGTIME[1], 'if(window.name=="IWORK")history.go(-1);', 'NR');
}else{
if( $_LOGFULLSTATUS && SETUP::$LogHistory['LogFullType']!=$_LOGFULLTYPE ) $_LOGFULLSTATUS = false;
$_NmGDF = $OriFichero;
$Fichero = $DFichero[0];
$OriFichero = $Fichero;
$Fichero = eScript( $Fichero );
$FicheroD = $Fichero;
eInit();
$__='{#}eDes{#}';
$_Accion='L'; include($Dir_.'_lista.gs');
eEnd();
}
}
if( $Opcion=='A' || $Opcion=='B' || $Opcion=='M' ){
foreach($_PHPSESSION as $k=>$v){
if( $_POST[$k]<>$v ) eMessage((($_PHPSESSIONMSG=='')?"(G{$Opcion}) Error de Sessión":$_PHPSESSIONMSG),'HSE');
}
$DimNomVar  = array_keys(  $_POST);
$DimValor   = array_values($_POST);
$DimValorIn = array_values($_POST);
$Dim = explode('|', $_FIELDSLIST);
$_FIELDSLIST = array();
for($t=0; $t<count($Dim); $t++){
$DimCampo = explode(',', $Dim[$t]);
$sa = $t;
if( $t>9 ) $sa = mb_chr(55+$t);
for($c=0; $c<count($DimCampo)-1; $c++){
$_FIELDSLIST[$DimCampo[$c]] = $sa;
}
}
$IndicePadre = '';
$Extraer = '';
$RegABuscar = '';
$ValorDB = array();
$nDB = 0;
$xCampos = array();
$xValores = array();
$DimValorIn = array();
ExtraeCampos();
for($n=0; $n<count($DimNomVar); $n++){
$DimValor[$n] = str_replace('"','&quot;',$DimValor[$n]);
$DimValorIn[$n] = str_replace('"','&quot;',$DimValorIn[$n]);
if( $_ConDBRange[$DimNomVar[$n]] ) $DimValor[$n] = stripslashes( $DimValor[$n] );
if( eSubstrCount($DimValor[$n], '" and ')==0 && !$_DBMEMO[$DimNomVar[$n]] ){
if( SS::isDriver('informix') ){
$DimValor[$n] = trim(stripslashes( $DimValor[$n] ));
}else{
if( DB::isDriver("oci") ){
$DimValor[$n] = trim(stripslashes( $DimValor[$n] ));
}else{
$DimValor[$n] = addslashes(trim(stripslashes( $DimValor[$n] )));
}
}
}
$tmp[0] = trim($DimNomVar[$n]);
$tmp[1] = $DimValor[$n];
if( $_SinUrlDecode[$tmp[0]] ){
$tmp[1] = trim($tmp[1]);
}else{
$tmp[1] = trim(urldecode($tmp[1]));
}
$_vF[$tmp[0]] = $tmp[1];
if( mb_substr($DimNomVar[$n],0,6)=="_FILE_" && $DimValor[$n]!="" ){
for($i=0; $i<count($DimNomVar); $i++){
if( $DimNomVar[$i]==mb_substr($DimNomVar[$n],6) ){
eExplodeLast($DimValor[$i], ".", $iz, $dch);
if( $dch!="" ){
$DimValor[$i] = $iz.".".mb_strtolower($dch);
$_POST[$DimNomVar[$i]] = $DimValor[$i];
$_vF[$DimNomVar[$i]] = $DimValor[$i];
}
break;
}
}
}
}
if( $_DBINI!='' ){
$sMSGANSWER = $_MSGANSWER;
$sMSGANSWEROK = $_MSGANSWEROK;
$_MSGANSWER = '';
$_MSGANSWEROK = '';
if( $_SAVEDATALIST!='' && isset($_SubListGetRecords) ){
include_once($Dir_.'formstatic.inc');
if( function_exists("UpdateSubList") ) UpdateSubList($Opcion);
$_SubListGetRecords = GrabaSubLista( $Opcion, true );
}
$tmpFile = GrabaTmp('g_dbini', $_DBINI, $LenDoc);
include($tmpFile);
_ShowError($php_errormsg, $tmpFile, $LenDoc);
unset($_DBINI); unset($tmpFile);
if( isset($_CHECKDELETE) && $_CHECKDELETE!='' ) include_once( $Dir_.'checkdelete.inc' );
$n=0;
foreach($_vF as $k=>$v){
$DimNomVar[$n] = $k;
$DimValor[$n] = $v;
$n++;
}
$_MSGANSWER = $sMSGANSWER;
$_MSGANSWEROK = $sMSGANSWEROK;
}
for($n=0; $n<count($DimNomVar); $n++){
if( $DimNomVar[$n][0]=='_' ) continue;
if( SS::isDriver('informix') ){
if( eSubstrCount('<>=', $DimValor[$n][0])==0 ) $DimValor[$n] = str_replace('"','""',$DimValor[$n]);
}
$tmp = array('','');
$tmp[0] = trim($_FIELDSLIST[$DimNomVar[$n]].'.'.$DimNomVar[$n]);
if( $DimValor[$n]=="" ) $DimValor[$n] = "NULL";
$tmp[1] = $DimValor[$n];
if( $_SinUrlDecode[mb_substr($tmp[0],2)] ){
$tmp[1] = trim($tmp[1]);
}else{
$tmp[1] = trim(urldecode($tmp[1]));
}
$s_vF = $tmp[1];
if( $tmp[1]=='NULL' ){
$tmp[1] = $tmp[1];
}else if( preg_match('/(\+|\-)/u', $_pField[$DimNomVar[$n]][2][0]) ){
$tmp[1] = ($tmp[1]*1);
}else if( $_pField[$DimNomVar[$n]][2]=="F4" && $tmp[1]=="" ){
$tmp[1] = 'NULL';
}else if( !DB::isDriver("oci") ){
$tmp[1] = '"'.$tmp[1].'"';
}else{
$tmp[1] = "'".str_replace("'","''",$tmp[1])."'";
}
$xAlias = $tmp[0][0];
if( $xAlias>'9' ) $xAlias = mb_ord($xAlias)-55;
if( mb_substr($tmp[0],2,3) == '___' ) continue;
if( $tmp[0][1]=='.' ){
$ValorDB[$nDB][0] = mb_substr( $tmp[0], 2 );
$ValorDB[$nDB][1] = $tmp[1];
$ValorDB[$nDB][2] = mb_chr(65+$xAlias);
$DimValorIn[$nDB] = $ValorDB[$nDB][1];
$_vF[ mb_substr($tmp[0],2) ] = $s_vF;
if( count($_DBSERIAL)>0 && $_DBSERIAL[1] == mb_substr( $tmp[0], 2 ) ){
$_DBSERIAL[2] = $tmp[1];
}
if( $Extraer!='' ) $Extraer .= ', ';
$Extraer .= mb_chr(65+$xAlias).mb_substr( $tmp[0], 1 );
if( $DimGrabar[$xAlias]!='' ) $DimGrabar[$xAlias] .= ',';
if( $DimInsert[$xAlias]!='' ) $DimInsert[$xAlias] .= '|';
if( SS::isDriver('informix') ){
}else{
if( !DB::isDriver("oci") && mb_strlen($tmp[1])==12 && mb_substr($tmp[1],3,1)=='-' && mb_substr($tmp[1],6,1)=='-' ){
$tmp[1] = '"'.mb_substr($tmp[1],7,4).mb_substr($tmp[1],3,4).mb_substr($tmp[1],1,2).'"';
}
}
$DimGrabar[$xAlias] .= mb_substr($tmp[0], 2).'='.$tmp[1];
$DimInsert[$xAlias] .= mb_substr($tmp[0], 2).'='.$tmp[1];
if( $_DBSERIAL[1]!=mb_substr($tmp[0], 2) ){
if( $xCampos[$xAlias]!='' ){
$xCampos[$xAlias] .= ', ';
$xValores[$xAlias] .= ', ';
}
$xCampos[$xAlias] .= mb_substr( $tmp[0], 2 );
$xValores[$xAlias] .= $tmp[1];
}
if( !empty($tmp[1]) && $tmp[1]<>"NULL" ){
if( !empty($RegABuscar) ) $RegABuscar .= ', ';
$RegABuscar .= mb_substr($tmp[0], 2).'='.$tmp[1];
$DimLong[$xAlias] += mb_strlen($tmp[1]) - 2;
}
if( mb_substr($tmp[0], 2)==$_DBINDEX && empty($IndicePadre) ){
$IndicePadre = $tmp[1];
}
if( $_DBINDEX2!='' ){
if( in_array($DimNomVar[$n], $DimIndice2) ){
if( preg_replace('/[0 .]/', '', $DimValor[$n])=='' && eSubstrCount($_DBINDEX2,',')==0 ){
}else{
if( $NTX2!='' ) $NTX2 .= ' and ';
if( DB::isDriver("oci") ){
$NTX2 .= $DimNomVar[$n]. "='" .str_replace("'","''",$DimValor[$n])."' ";
}else{
$NTX2 .= $DimNomVar[$n]. '="' .$DimValor[$n]. '" ';
}
}
}
}
if( $_DBINDEX3!='' ){
if( in_array($DimNomVar[$n], $DimIndice3) ){
if( preg_replace('/[0 .]/', '', $DimValor[$n])=='' && eSubstrCount($_DBINDEX3,',')==0 ){
}else{
if( $NTX3!='' ) $NTX3 .= ' and ';
if( DB::isDriver("oci") ){
$NTX3 .= $DimNomVar[$n]. "='" .str_replace("'","''",$DimValor[$n])."' ";
}else{
$NTX3 .= $DimNomVar[$n]. '="' .$DimValor[$n]. '" ';
}
}
}
}
$nDB++;
}else{
eMessage( str_replace('#',$tmp[0],$__Lng[96]), 'HSE');
}
}
$NTX = str_replace('A.','',$IndiceMultiple);
if( $Opcion=='M' && $_ModCampoIndice ){
$tmp = explode('|',$_UNIQUE_);
$NTX = '';
$Busca = '';
for( $i=0; $i<count($tmp); $i+=2 ){
if( $NTX!='' ) $NTX .= ' and ';
if( $Busca!='' ) $Busca .= ' and ';
if( DB::isDriver("oci") ){
$NTX   .= $tmp[$i]."='".str_replace("'","''",$tmp[$i+1])."' ";
$Busca .= $tmp[$i]."='".str_replace("'","''",$tmp[$i+1])."' ";
}else{
$NTX .= $tmp[$i].'="'.$tmp[$i+1].'"';
$Busca .= $tmp[$i].'="'.$tmp[$i+1].'"';
}
}
}
if( eSubstrCount('ABM',$Opcion)>0 && $_SESSION["_UpdateIntervalDB"]>0 ){
if( time()<$_SESSION["_UpdateDB"] ){
error_log(date('Y-m-d H:i:s')." ROBOT ".S::$_User."\n", 3, '../_tmp/err/_robot.err');
eInit();
eEnd();
}
$_SESSION["_UpdateDB"] = time()+($_SESSION["_UpdateIntervalDB"]*2);
}
$xTabla  = array();
$xGrabar = array();
$xInsert = array();
$xLong   = array();
$xxCampos  = array();
$xxValores = array();
$xInsertLog = array();
$xGrabarLog = array();
for( $n=0; $n<$TotalHojas; $n++ ){
if( !in_array( $DimTabla[$n], $xTabla ) ){
array_push( $xTabla		, $DimTabla[$n] );
array_push( $xGrabar	, $DimGrabar[$n] );
array_push( $xInsert	, $DimInsert[$n] );
array_push( $xLong		, $DimLong[$n] );
array_push( $xxCampos	, $xCampos[$n] );
array_push( $xxValores	, $xValores[$n] );
array_push( $xInsertLog	, $DimInsert[$n] );
array_push( $xGrabarLog	, $DimGrabar[$n] );
}else{
$v=0;
for( $i=0; $i<count($xTabla); $i++ ){
if( $DimTabla[$n] == $xTabla[$i] ){
if( trim($DimGrabar[$n])!='' || trim($DimInsert[$n])!='' ){
$xGrabar[$v]	.= ','.$DimGrabar[$n];
$xInsert[$v]	.= '|'.$DimInsert[$n];
$xLong[$v]		+= $DimLong[$n];
$xxCampos[$v]	.= ', '.$xCampos[$n];
$xxValores[$v]	.= ', '.$xValores[$n];
$xInsertLog[$v]	.= '|'.$DimInsert[$n];
$xGrabarLog[$v]	.= ','.$DimGrabar[$n];
$v++;
break;
}
}
}
}
}
if( isset($_POST["_FIELDSWITHFILES"]) ){
for( $v=0; $v<count($xxCampos); $v++ ){
$ListaCampos = ','.str_replace(' ','',$xxCampos[$v]).',';
$nf=0;
$tmp = explode('|',$_POST["_FIELDSWITHFILES"]);
for( $n=0; $n<count($tmp)-1; $n++ ){
if( eSubstrCount( $ListaCampos, ','.$tmp[$n].',' ) > 0 ){
if( $_POST[$tmp[$n]]!='' && $_UPLOADFILE[$tmp[$n]]['oDIR']=='' ){
$FileTmp = '../_tmp/zip/'.S::$_User.'_'.($nf++);
$data = file_get_contents($FileTmp);
$xInsert[$v]	.= '|'.$_UPLOADFILE[$tmp[$n]]['NOMBRE']."='".addslashes($data)."'";
$xGrabar[$v]	.= ", ".$_UPLOADFILE[$tmp[$n]]['NOMBRE']."='".addslashes($data)."'";
$xxCampos[$v]	.= ', '.$_UPLOADFILE[$tmp[$n]]['NOMBRE'];
$xxValores[$v]	.= ", '".addslashes($data)."'";
$_POST["_FIELDSWITHFILES"] = trim(str_replace( $tmp[$n].'|', '', $_POST["_FIELDSWITHFILES"] ));
}
}
}
}
}
for($n=0; $n<count($xTabla); $n++){
if( $n==0 ){
if( trim($NTX)=='' ){
$_TReg = 0;
}else{
$_TReg = DB::count($xTabla[$n], $NTX);
}
$DimTReg[$n] = $_TReg;
}
if( $n>0 && ($xGrabar[$n]!='' || $xInsert[$n]!='') ){
$xGrabar[$n] .= ','.$_DBINDEX.'='.$IndicePadre;
$xInsert[$n] .= '|'.$_DBINDEX.'='.$IndicePadre;
if( $_DBINDEX<>$_DBSERIAL[1] ){
$xxCampos[$n]  .= ', '.$_DBINDEX;
$xxValores[$n] .= ', '.$IndicePadre;
}
}
}
if( $Opcion=='M' || $Opcion=='B' ){
if( isset($_POST['_MD5']) ){
if( $_POST['_MD5'] != DB::getHashRecord($xTabla, $NTX) ) eMessage($__Lng[93], 'HSE');
}
if( $_PHPCHECK<>'' ){
$_vF = array();
for( $n=0; $n<count($xTabla); $n++ ){
DB::query( "select * from {$xTabla[$n]} where {$NTX}" );
$_vF = array_merge( $_vF, DB::get() );
}
$tmpFile = GrabaTmp('f_phpcheck', $_PHPCHECK, $LenDoc, $_FILE_PHPCHECK);
include( $tmpFile );
_ShowError( $php_errormsg, $tmpFile, $LenDoc );
unset( $_PHPCHECK );
}
}
$DBAcceso = '';
if( eSubstrCount('ABM', $Opcion)>0 ){
$tmp = explode(',', $_DBINDEX);
for($n=0; $n<count($tmp); $n++){
if( $DBAcceso!='' ) $DBAcceso .= ',';
$DBAcceso .= $tmp[$n].'='.${$tmp[$n]};
}
}
switch( $Opcion ){
case 'A':
if( $DimTReg[0]>0 ) eMessage('~DR', 'EHS', $_MSGTIME[1], 'if(window.name=="IWORK")history.go(-1);', 'DR');
if( $NTX2!='' ){
if( DB::count($_DBTABLE, $NTX2) > 0 ){
eMessage('~DR', 'EHS', $_MSGTIME[1], 'if(window.name=="IWORK")history.go(-1);', 'DR');
}
}
if( $NTX3!='' ){
if( DB::count($_DBTABLE, $NTX3) > 0 ){
eMessage('~DR', 'EHS', $_MSGTIME[1], 'if(window.name=="IWORK")history.go(-1);', 'DR');
}
}
if( $_DEBUG==5 || $_DEBUG==6 ) include($Dir_.'debug5.inc');
for($n=0; $n<count($xTabla); $n++){
if( $xLong[$n]>0 ){
if( trim($NTX)=='' ){
$_TReg = 0;
}else{
$_TReg = DB::count($xTabla[$n], $NTX);
}
if( $_TReg==0 ){
if( count($_DBSERIAL)>0 ){
if( $_DBSERIAL[0]!=$xTabla[$n] ){
$xxCampos[$n]  = $_DBSERIAL[1].','.$xxCampos[$n];
$xxValores[$n] = $_DBSERIAL[2].','.$xxValores[$n];
}
}
if( $n>0 ){
$sDBSEQUENCE = $_DBSEQUENCE;
$_DBSEQUENCE = '';
$sDBSERIAL   = $_DBSERIAL;
$_DBSERIAL   = array();
}
DB::query("insert into {$xTabla[$n]} ({$xxCampos[$n]}) values ({$xxValores[$n]})");
if( $n>0 ){
$_DBSEQUENCE = $sDBSEQUENCE;
$_DBSERIAL   = $sDBSERIAL;
}
$_OkDBINSERT = true;
if( count($_DBSERIAL)>0 && $_DBSERIAL[0]==$xTabla[$n] ){
for($i=0; $i<count($_IdInsert); $i++){
if( $_IdInsert[$i][0]==$_DBSERIAL[0] ){
$_DBSERIAL[2] = $_IdInsert[$i][1];
$_nSerial = $_DBSERIAL[2];
$_IdRegistro[$xTabla[$n]] = $_nSerial;
$_vF[$_DBSERIAL[1]] = $_nSerial;
}
}
$DBAcceso .= $_nSerial;
}
}else{
DB::query("update {$xTabla[$n]} set {$xGrabar[$n]} {$NTX}");
}
if( $n==0 ){
if( count($_DBLOG)>0 ){
for($i=0; $i<count($xTabla); $i++){
if( count($_DBSERIAL)>0 && $_DBSERIAL[0]==$xTabla[$i] ){
if( DB::isDriver("oci") ){
$OldSerial = trim($_DBSERIAL[1])."=''";
$NewSerial = trim($_DBSERIAL[1])."='".$_nSerial."'";
}else{
$OldSerial = trim($_DBSERIAL[1]).'=""';
$NewSerial = trim($_DBSERIAL[1]).'="'.$_nSerial.'"';
}
}else{
}
}
}
}
}
}
if( $_SAVEDATALIST!='' ){
include_once($Dir_.'formstatic.inc');
if( function_exists("UpdateSubList") ) UpdateSubList($Opcion);
GrabaSubLista($Opcion);
}
if( $_POST['_ISUBLISTSERIAL']!='' ){
$Dim = explode('|', $_POST['_ISUBLISTSERIAL']);
for($n=0; $n<count($Dim)-1; $n++){
$Dim[$n] = trim($Dim[$n]);
if( mb_substr($Dim[$n],-1)!=')' ){
list(,$t,$k,$v,$iSubListSufijo) = explode(',', $Dim[$n]);
}else{
$eDim = explode(',',$Dim[$n]);
$t = $eDim[1];
$k = $eDim[2];
$v = $eDim[3];
for($i=4; $i<count($eDim); $i++) $v .= ','.$eDim[$i];
}
$k = trim($k);
if( count($_DBSERIAL)>0 && $_DBSERIAL[0]==$_DBTABLE ) $_vF[$k] = $_nSerial;
$v = str_replace("&#39;", "'", $v);
if( $iSubListSufijo<>"" ){
DB::query("update {$t}{$iSubListSufijo} set {$k}='".$_vF[$k]."' where {$k}={$v}");
$v = $_vF[trim($k)];
DB::query("insert into {$t} (select * from {$t}{$iSubListSufijo} where {$k}={$v})");
DB::query("delete from {$t}{$iSubListSufijo} where {$k}={$v}");
}else{
DB::query("update {$t} set {$k}='".$_vF[$k]."' where {$k}={$v}");
}
}
}
Estadistica('gFi', 0, $DBAcceso, $xTabla[0]);
if( $_POST["_FIELDSWITHFILES"]!='' ) _FileGetContents($Opcion);
if( false && count($_ObjetoSQL)>0 && count($_SaveList)==0 && count($_SaveOnLine)==0 ){
for( $w=0; $w<count($_ObjetoSQL); $w++ ){
$xSql = mb_strtolower( $_ObjetoSQL[$w] );
list( ,$tmp ) = explode( ' from ', $xSql );
list( $wTabla, $wWhere ) = explode( ' where ', $tmp );
$wTabla = trim($wTabla);
list( $wWhere, ) = explode( ' order by ', $wWhere );
$wWhere = trim($wWhere);
while( eSubstrCount( $wWhere, '{' ) > 0 ){
$ini = mb_strpos($wWhere,'{')+1;
$fin = mb_strpos($wWhere,'}');
$sCampo = trim( mb_substr( $wWhere, $ini, $fin-$ini ));
if( $_IdRegistro[$xTabla[0]] > 0 ){
$wWhere = str_replace( '{'.$sCampo.'}', $_IdRegistro[$xTabla[0]], $wWhere );
}else{
$wWhere = $NTX;
}
}
$wSql = "update {$wTabla} set {$wWhere}, conexion=0 where conexion=".$GLOBALS['_Connection_'];
DB::query( $wSql );
}
}
_gsLastInsert($NTX, DB::id());
$_LOGANSWER["answer"] = "ok";
if( $_DBEND!='' ){
$tmpFile = GrabaTmp('g_dbend', $_DBEND, $LenDoc);
include($tmpFile);
_ShowError($php_errormsg, $tmpFile, $LenDoc);
$_DBEND = '';
}
if( $_GET["_SUBINSERT"]==1 ){
$xSUBINSERT .= "_WOPENER._Celda = _WOPENER._FilaLastInsert.cells[0];";
$tmp = explode(",", $_DBINDEX);
for($n=0; $n<count($tmp); $n++){
$xSUBINSERT .= "_WOPENER.ePF('{$tmp[$n]}', '".str_replace("'", CHR92."'",$_vF[$tmp[$n]])."');";
}
$_JSSTART = $xSUBINSERT;
}
$AyadeSerial = ((isset($_GET['_ISUBLIST']) && count($_DBSERIAL)>0 ) ? "_WOPENER._PutSerial('{$_DBSERIAL[1]}',{$_nSerial});" : '');
$_MSGANSWEROK = true;
eMessage('~S', ((isset($_GET['_STOP'])) ? 'HS':''), $_MSGTIME[0], $AyadeSerial);
$Opcion = 'a'; $SubOp = 'A'; $Titulo='INSERTAR #';
break;
case 'M':
if( $DimTReg[0]!=1 ) eMessage('~DR', 'EHS', $_MSGTIME[1],'', 'DR');
if( $NTX2!='' ){
if( DB::count($_DBTABLE, $NTX2.' and not ('.$NTX.')') > 0 ){
eMessage('~DR', 'EHS', $_MSGTIME[1], 'if(window.name=="IWORK")history.go(-1);', 'DR');
return;
}
}
if( $NTX3!='' ){
if( DB::count($_DBTABLE, $NTX3.' and not ('.$NTX.')') > 0 ){
eMessage('~DR', 'EHS', $_MSGTIME[1], 'if(window.name=="IWORK")history.go(-1);', 'DR');
return;
}
}
if( $_DEBUG==5 || $_DEBUG==6 ) include( $Dir_.'debug5.inc' );
if( isset($_LastValue) ){
DB::query("select {$_LastValue} from ".$xTabla[0].' where '.$NTX);
$_LastValue = DB::get();
}
if( count($_DBLOG)>0 ){
for( $n=0; $n<count($xTabla); $n++ ){
DB::query('select * from '.$xTabla[$n].' where '.$NTX);
$xxGrabar = ','.$xGrabarLog[$n];
$r = DB::get();
foreach( $r as $k=>$v ){
$v = trim($v);
if( preg_match('/([0]{4})-([0]{2})-([0]{2})/u', $v) ) $v = "";
if( !DB::isDriver("oci") ){
$v = str_replace("'", "\\'", $v);
$v = str_replace('"', '\\"', $v);
$xxGrabar = str_replace(','.$k.'="'.$v.'",', ',', $xxGrabar);
$xxGrabar = str_replace(','.$k.'="'.$v.'"' , ',', $xxGrabar);
}else{
$v = str_replace("'", "''", $v);
$xxGrabar = str_replace(','.$k."='".$v."',", ',', $xxGrabar);
$xxGrabar = str_replace(','.$k."='".$v."'" , ',', $xxGrabar);
}
}
if( $xxGrabar[0]==',' ) $xxGrabar = mb_substr($xxGrabar,1);
if( mb_substr($xxGrabar,-1)==',' ) $xxGrabar = mb_substr($xxGrabar,0,-1);
if( $xxGrabar<>'' ){
}
}
}
for($n=0; $n<count($xTabla); $n++){
$_TReg = DB::count($xTabla[$n], $NTX);
if( $_TReg==0 && $xLong[$n]>0 ){
if( count($_DBSERIAL)>0 && $_DBSERIAL[0]!=$xTabla[$n] ){
$xxCampos[$n]  = $_DBSERIAL[1].','.$xxCampos[$n];
$xxValores[$n] = $_DBSERIAL[2].','.$xxValores[$n];
}
if( $n>0 ){
$sDBSEQUENCE = $_DBSEQUENCE;
$_DBSEQUENCE = '';
$sDBSERIAL   = $_DBSERIAL;
$_DBSERIAL   = array();
}
DB::query("insert into {$xTabla[$n]} ({$xxCampos[$n]}) values ({$xxValores[$n]})");
if( $n>0 ){
$_DBSEQUENCE = $sDBSEQUENCE;
$_DBSERIAL   = $sDBSERIAL;
}
}else if( $_TReg==1 ){
if( $xTabla[$n]==$_DBSERIAL[0] ){
if( !DB::isDriver("oci") ){
$pos = mb_strpos($xGrabar[$n], $_DBSERIAL[1].'="');
}else{
$pos = mb_strpos($xGrabar[$n], $_DBSERIAL[1]."='");
}
if( $pos===false ){
}else{
for($pi=$pos; $pi>1; $pi--){
if( mb_substr($xGrabar[$n], $pi, 1)==',' ) break;
}
for($pf=$pos+mb_strlen($_DBSERIAL[1].'="'); $pf<mb_strlen($xGrabar[$n]); $pf++){
if( mb_substr( $xGrabar[$n], $pf, 1 ) == ',' ) break;
}
$xGrabar[$n] = trim(str_replace( mb_substr( $xGrabar[$n], $pi, $pf-$pi ), '', $xGrabar[$n] ));
if( $xGrabar[$n][0]==',' ) $xGrabar[$n] = mb_substr($xGrabar[$n],1);
}
}
if( $_FILELOG[$xTabla[$n]] ){
$_FILELOG[$xTabla[$n]] = array();
DB::query('select * from '.$xTabla[0].' where '.$NTX);
$cur = DB::get();
foreach($cur as $k=>$v){
$_FILELOG[$xTabla[$n]][$k] = $v;
}
}
if( trim($xGrabar[$n])!='' ){
DB::query("update {$xTabla[$n]} set {$xGrabar[$n]} where {$NTX}");
}
}
}
if( $_SAVEDATALIST!='' ){
include_once($Dir_.'formstatic.inc');
if( function_exists("UpdateSubList") ) UpdateSubList($Opcion);
GrabaSubLista($Opcion);
}
Estadistica('gFi', 0, $DBAcceso, $xTabla[0]);
if( $_POST["_FIELDSWITHFILES"]!='' ) _FileGetContents($Opcion);
_gsLastInsert($NTX);
$_LOGANSWER["answer"] = "ok";
if( $_DBEND!='' ){
$tmpFile = GrabaTmp('g_dbend', $_DBEND, $LenDoc);
include($tmpFile);
_ShowError($php_errormsg, $tmpFile, $LenDoc);
$_DBEND = '';
}
$_MSGANSWEROK = true;
eMessage('~U', ((isset($_GET['_STOP'])) ? 'HS':''), $_MSGTIME[0], $tmpAutoMenu);
$Opcion = 'm'; $SubOp = 'mR';
break;
case 'B':
if( $DimTReg[0]!=1 ) eMessage( '~DR', 'EHS', $_MSGTIME[1],'', 'DR' );
if( $_DBBAKDELETE ){
for( $n=0; $n<count($xTabla); $n++ ){
if( mb_substr($xTabla[$n],-4)!='_dlt' ){
if( DB::count( $xTabla[$n].'_dlt', $NTX ) > 0 ){
DB::query( "delete from {$xTabla[$n]}_dlt where {$NTX}" );
}
DB::query( "insert into {$xTabla[$n]}_dlt select * from {$xTabla[$n]} where {$NTX}" );
if( $_DBBakDeleteUpdate!='' ){
list( $xFieldFecha, $xFieldUser ) = explode(',',$_DBBakDeleteUpdate);
$xInstante = ( mb_substr(trim($xFieldFecha),0,3)=='dt_' ) ? date('Y-m-d') : date('Y-m-d H:i:s');
DB::query( "update {$xTabla[$n]}_dlt set {$xFieldFecha}='{$xInstante}', {$xFieldUser}='{$_User}' where {$NTX}" );
}
}else{
if( DB::count( mb_substr($xTabla[$n],0,-4), $NTX ) == 0 ){
DB::query( "insert into ".mb_substr($xTabla[$n],0,-4)." select * from {$xTabla[$n]} where {$NTX}" );
if( $_DBBakDeleteUpdate!='' ){
list( $xFieldFecha, $xFieldUser ) = explode(',',$_DBBakDeleteUpdate);
$xInstante = ( mb_substr(trim($xFieldFecha),0,3)=='dt_' ) ? date('Y-m-d') : date('Y-m-d H:i:s');
DB::query( "update ".mb_substr($xTabla[$n],0,-4)." set {$xFieldFecha}='{$xInstante}', {$xFieldUser}='{$_User}' where {$NTX}" );
}
}else{
eMessage( $__Lng[94], 'EHS', '','', 'FND' );
}
}
}
}
if( count($_DBLOG)>0 ){
for( $n=0; $n<count($xTabla); $n++ ){
}
}
if( count($_Fichero)>0 ){
$xNomFileBak = '';
for( $nf=0; $nf<count($_Fichero); $nf++ ){
if( $_Fichero[$nf][0]=='_' ) continue;
if( $_UPLOADFILE[$_Fichero[$nf]]['NOMBRE']!=$_Fichero[$nf] ){
$ListCampos = $_DBSERIAL[1].','.$_Fichero[$nf];
}else{
$ListCampos = $_UPLOADFILE[$_Fichero[$nf]]['NOMBRE'];
}
DB::query("select {} from {$_DBTABLE} where {$NTX}");
$row = DB::get();
$_vF = &$row;
if( $_UPLOADFILE[$_Fichero[$nf]]['NOMBRE']!=$_Fichero[$nf] ){
$NomExt = mb_substr( $row[$_Fichero[$nf]], mb_strrpos($row[$_Fichero[$nf]], '.' ));
$xNomFile = $row[$_UPLOADFILE[$_Fichero[$nf]]['NOMBRE']].$NomExt;
$xNomFileBak = $row[$_UPLOADFILE[$_Fichero[$nf]]['NOMBRE']].'.bak';
}else{
$xNomFile = $row[$_Fichero[$nf]];
}
$xNomFile = trim($xNomFile);
$xNomFileBak = _NmFileConPrefijo( $xNomFileBak, $_UPLOADFILE[$_Fichero[$nf]]['PREFIJO'] );
$xNomFile = _NmFileConPrefijo( $xNomFile, $_UPLOADFILE[$_Fichero[$nf]]['PREFIJO'] );
if( trim($xNomFile)!='' && file_exists( $_UPLOADFILE[$_Fichero[$nf]]['DIR'].'/'.$xNomFile ) ){
if( unlink( $_UPLOADFILE[$_Fichero[$nf]]['DIR'].'/'.$xNomFile ) == false ){
eMessage( $__Lng[95], 'EHS', '','', 'FND' );
}
}
@unlink( $_UPLOADFILE[$_Fichero[$nf]]['DIR'].'/'.$xNomFileBak );
}
}
if( $_SAVEDATALIST!='' ){
include_once( $Dir_.'formstatic.inc' );
if( function_exists("UpdateSubList") ) UpdateSubList($Opcion);
GrabaSubLista( $Opcion );
}
if( isset($_ISUBLISTDELETE) ){
include_once(DIREDES.'isublist.inc');
list( $iFile, $iRelacion ) = explode('|',$_ISUBLISTDELETE);
_ISubListDelete( $iFile, $iRelacion, $_POST[$iRelacion] );
}
for( $n=0; $n<count($xTabla); $n++ ){
$_TReg = DB::count( $xTabla[$n], $NTX );
if( $_TReg == 1 ){
DB::query("delete from {$xTabla[$n]} where {$NTX}");
}
}
Estadistica( 'gFi', 0, $DBAcceso, $xTabla[0] );
_gsLastInsert($NTX);
$_LOGANSWER["answer"] = "ok";
if( $_DBEND!='' ){
$tmpFile = GrabaTmp( 'g_dbend', $_DBEND, $LenDoc );
include( $tmpFile );
_ShowError( $php_errormsg, $tmpFile, $LenDoc );
$_DBEND = '';
}
$_MSGANSWEROK = true;
if( mb_substr($xTabla[0],-4)=='_dlt' ){
eMessage( '~R', ((isset($_GET['_STOP'])) ? 'HS':''), $_MSGTIME[0] );
}else{
eMessage( '~D', ((isset($_GET['_STOP'])) ? 'HS':''), $_MSGTIME[0] );
}
$Opcion = 'b'; $SubOp = 'bR';
break;
default:
if( $_DBEND!='' ){
$tmpFile = GrabaTmp('g_dbend', $_DBEND, $LenDoc);
include($tmpFile);
_ShowError($php_errormsg, $tmpFile, $LenDoc);
$_DBEND = '';
}
}
$SoloQue = true;
}else{
if( $_DBEND!='' ){
$tmpFile = GrabaTmp('g_dbend', $_DBEND, $LenDoc);
include($tmpFile);
_ShowError($php_errormsg, $tmpFile, $LenDoc);
$_DBEND = '';
}
}
?>