<?PHP
date_default_timezone_set('Europe/Madrid');
define('_ERROR_REPORTING', 5);
define('_TRACK_ERRORS', false);
ini_set('track_errors', false);
error_reporting(_ERROR_REPORTING);
if( isset($_GET['PKSERVER']) ){
if( file_exists("../_datos/config/".$_GET['PKSERVER'].".edes") ){
die("Test OK|"._IDSRV());
}
}
if( $_POST['TO_UPDATE']=='test' ) die("Test OK|"._IDSRV());
foreach($_GET  as $k=>$v) $GLOBALS[$k] = $v;
foreach($_POST as $k=>$v) $GLOBALS[$k] = $v;
$_Tron = false;
if( !isset($_ENV['SYSDB']) ){
if( SETUP::$System['Multitenancy'] ){
$file = "../_datos/config/share.ini";
if( file_exists($file) ){
include($file);
$_ENV['SYSDB'] = $_SqlDiccionario;
if( SETUP::$System['SharedTables']!="" ){
$tmp = trim(str_replace(" ","",SETUP::$System['SharedTables']));
$dim = explode(",", $tmp);
}else{
SETUP::$System['Multitenancy'] = array();
}
if( $_ENV['SYSDB']!="" && mb_substr($_ENV['SYSDB'],-1)!="." ){
$_ENV['SYSDB'] .= ".";
SETUP::$System['Multitenancy'] = array_merge(SETUP::$System['Multitenancy'], explode(",","gs_op,gs_op_ico,gs_op_lng,gs_tree,gs_tree_op,gs_tpermission,gs_activity,gs_language,gs_entidad,gs_grupo,gs_campo,gs_color,gs_store,gs_toperacion,gs_pack,gs_error"));
}else{
$_ENV['SYSDB'] = "";
}
}else if( !SETUP::$System['Multitenancy'] ){
$_ENV['SYSDB'] = "";
}
}
}
if( !isset($_ENV['SYSDB']) ){
$_ENV['SYSDB'] = "";
}
if( $_POST['TO_UPDATE']=='eDes' ){
$_GET['FILE'] = $_POST['file_name'];
$_GET['IDSRV'] = $_POST['IDSRV'];
}
if( $_Tron ){
error_log(date('Y-m-d H:i:s')."\n",3,'_upload.info');
error_log('QUERY..................: '.$_SERVER['QUERY_STRING']		."\n",3,'_upload.info');
}
$Dir_ = dirname(__FILE__).'/';
if( WINDOW_OS ) $Dir_ = str_replace('\\','/',$Dir_);
if( isset( $_GET['FILELOCAL'] ) ) $_FILES['file']['tmp_name'] = $_GET['FILELOCAL'];
if( $_Tron ){
error_log('FILELOCAL..............: '.$_GET['FILELOCAL']			."\n",3,'_upload.info');
error_log('_FILES[files][tmp_name]: '.$_FILES['file']['tmp_name']	.' ('.count($_FILES).")\n",3,'_upload.info');
error_log('count($_FILES).........: '.count($_FILES)				."\n",3,'_upload.info');
error_log('FILE...................: '.$_GET['FILE']					."\n",3,'_upload.info');
error_log('IDSRV..................: '.$_GET['IDSRV']				."\n",3,'_upload.info');
error_log('MD5 PC.................: '.$_GET['MD5']					."\n",3,'_upload.info');
error_log('Dir_...................: '.$Dir_							."\n",3,'_upload.info');
foreach( $_FILES as $k=>$v ){
error_log('   _FILES['.$k."]\n",3,'_upload.info');
foreach( $v as $k2=>$v2 ) error_log('   _FILES: '.$k2.' = '.$v2."\n",3,'_upload.info');
if( $_FILES[$k]["error"] > 0 ){
die("ERROR ".$_FILES[$k]["error"]);
}
}
}
if( count($_FILES)>0 ){
$CacheON = eFileGetVar("System.Cache");
$DirApli = GetCWD();
$DirApli = str_replace( '\\', '/', $DirApli );
$DirApli = str_replace( REM, '/', $DirApli );
if( mb_substr($DirApli,-1)=='/' ) $DirApli = mb_substr($DirApli,0,-1);
$tmp = explode('/',$DirApli);
$DirApli = $tmp[count($tmp)-2];
if( $_Tron ) error_log('DirApli: '.$DirApli."\n",3,'_upload.info');
$NomFile = $_GET['FILE'];
if( mb_substr($NomFile,0,23)=='/_bak_/update/_update_.' ){
$MacroFile = $_FILES['file']['tmp_name'];
if( $_Tron ) eTrace('PROCESO con MacroFile: '.$MacroFile);
}else{
if( $_Tron ) eTrace('PROCESO normal: '.$NomFile);
$MacroFile = '';
}
if( $MacroFile!='' ){
if( $_Tron ) eTrace( 'Long MacroFile: '.filesize($MacroFile) );
$sDir = '../_bak_/update/';
if( !is_dir( $sDir ) ) mkdir( $sDir, 0777 );
$MacroFile = '..'.$_GET['FILE'];
move_uploaded_file( $_FILES['file']['tmp_name'], $MacroFile );
clearstatcache();
if( $_Tron ) eTrace( 'MacroFile:'.$MacroFile );
$MaxFileSize = filesize($MacroFile);
$fp = fopen( $MacroFile, 'r' );
}
$nd = 0;
do{
if( $MacroFile!='' ){
$LongNombre = (int)fread( $fp, 2 );
$NomFile = fread( $fp, $LongNombre );
$LongFile = (int)fread( $fp, 8 );
$nd++;
$FileTemp = '../_tmp/_update_.'.$nd;
$_FILES['file']['tmp_name'] = $FileTemp;
file_put_contents($FileTemp, fread($fp, $LongFile));
clearstatcache();
if( $_Tron ){
eTrace('FileTemp: '.$FileTemp); eTrace('LongNombre: '.$LongNombre); eTrace('Nombre: '.$NomFile); eTrace( 'LongFile: '.$LongFile ); eTrace(' > Posición: '.ftell($fp) );
}
}
if( mb_substr($NomFile,0,4)=='[OP]' ){
$tmp = explode('~',mb_substr($NomFile,4));
$sql = "update {$_ENV['SYSDB']}gs_op set show_type='{$tmp[2]}' where cd_gs_op='{$tmp[1]}'";
if( $_Tron ) error_log("SQL: {$sql}\n", 3, '_upload.info');
SS::query($sql);
}else{
if( $_Tron ) error_log("NomFile: {$NomFile}\n",3,'_upload.info');
if( $CacheON ){
$dir = "../_tmp/cch/";
if( is_dir($dir) ){
if( $dh = opendir($dir) ){
while( ($file = readdir($dh))!==false ){
@unlink($dir.$file);
}
closedir($dh);
}
}
}
if( mb_substr($NomFile,0,2)==REM ){
if( $_Tron ) error_log('Tipo: '.REM."\n",3,'_upload.info');
$NomFile = '../../'.$DirApli.'.file'.mb_substr($NomFile,1);
}else if( mb_substr($NomFile,0,8)=='/../lib/' ){
if( $_Tron ) error_log('Tipo: '.'/lib/'."\n",3,'_upload.info');
$NomFile = '..'.$NomFile;
}else if( $NomFile[0]=='/' ){
if( $_Tron ) error_log('Tipo: '.'/'."\n",3,'_upload.info');
$NomFile = '..'.$NomFile;
}else if( $NomFile[0]=='$' ){
if( $_Tron ) error_log('Tipo: $'."\n",3,'_upload.info');
if( $_Tron ) error_log('IDSRV: '._IDSRV().' = '.$_GET['IDSRV']."\n",3,'_upload.info');
if( _IDSRV()<>$_GET['IDSRV'] ){
error_log('pcIDSRV 1: '.$_GET['IDSRV']."\n",3,'_upload.info');
error_log('srIDSRV 1: '._IDSRV(true)  ."\n",3,'_upload.info');
die('ERROR IDSRV');
}
$NomFile = DIREDES.mb_substr($NomFile,1);
}else if( $NomFile[0]=='=' ){
$NomFile = str_replace('\\','/',$NomFile);
$NomFile = str_replace('../','',$NomFile);
$NomFile = '../../'.mb_substr($NomFile,1);
}else{
if( $_Tron ) error_log('Tipo: else'."\n",3,'_upload.info');
if( $_Tron ) error_log('IDSRV: '._IDSRV().' = '.$_GET['IDSRV']."\n",3,'_upload.info');
if( _IDSRV()<>$_GET['IDSRV'] ){
error_log('pcIDSRV 2: '.$_GET['IDSRV']."\n",3,'_upload.info');
error_log('srIDSRV 2: '._IDSRV(true)  ."\n",3,'_upload.info');
die('ERROR IDSRV');
}
$NomFile = '../d/'.$NomFile;
}
if( $_Tron ) error_log("File Real: {$NomFile}\n",3,'_upload.info');
$oFile = $_FILES['file']['tmp_name'];
if( eSubstrCount( $NomFile.'/', '/crypt/' )>0 ){
$xNomFile = _NmFileConPrefijo( $NomFile, '' );
list( $Clave, $Ext ) = _UnPath( $NomFile );
list(,$xNomFile) = explode('/',$Clave);
copy( $oFile, '../_tmp/zip/'.$xNomFile );
$oFile = '../_tmp/zip/'.$xNomFile;
$xNomFile = mb_substr($xNomFile,0,(mb_strlen($Ext)+1)*-1);
$dFile = '../_tmp/zip/'.$xNomFile;
$Clave = md5($Clave);
if( LINUX_OS ){
$ExeZip = "zip -9 -P {$Clave} -j ".$dFile." ".$oFile;
}else{
$ExeZip = eScript('$win/zip.exe')." -9 -P {$Clave} -j ".$dFile." ".$oFile;
}
$Dim = array();
exec( $ExeZip, $Dim );
@unlink($dFile.'.'.$Ext);
@unlink($oFile);
$FileTmp = $dFile.'.zip';
$df = fopen( $FileTmp, 'r+' );
fwrite( $df, mb_chr(rand(48,127)).mb_chr(rand(48,127)) );
fclose( $df );
$oFile = $FileTmp;
}
if( !move_uploaded_file($oFile, $NomFile) ){
copy($oFile, $NomFile);
@unlink($oFile);
}
if( $_Tron ) eTrace('Mover File de: "'.$oFile.'" a "'.$NomFile.'"');
if( $_GET['MD5']!='' ){
if( $_Tron ){
error_log('MD5 PC.....: '.$_GET['MD5']			."\n",3,'_upload.info');
error_log('MD5 Server.: '.md5_file( $NomFile ) 	."\n",3,'_upload.info');
}
if( $_GET['MD5']<>md5_file($NomFile) ){
die('ERROR AL SUBIR EL FICHERO Al SERVIDOR');
}
}
}
if( $NomFile=='../tree/_gs_op_.txt' || $NomFile=='../tree/_gs_tree_.txt' ){
if( $_Tron ) error_log("Actualiza tabla: {$NomFile}\n",3,'_upload.info');
$TABLA = $_ENV['SYSDB'].(($NomFile=='../tree/_gs_op_.txt')?'gs_op':'gs_tree');
$FICHERO = $NomFile;
if( $_Tron ) error_log("Borra registros de: {$TABLA}\n",3,'_upload.info');
if( SS::count($TABLA)>0 ) SS::query("delete from {$TABLA}");
$TReg = 0;
if( $_Tron ) error_log("Abre fichero de: {$FICHERO}\n",3,'_upload.info');
$fd = fopen($FICHERO, 'r');
while( ($txt = fgets($fd,50000)) ){
$Valores = "'".str_replace('|', "','", chop($txt))."'";
$sql = "insert into {$TABLA} values ( $Valores )";
if( $_Tron ) error_log("SQL: {$sql}\n",3,'_upload.info');
SS::query($sql);
$TReg++;
}
fclose($fd);
if( $_Tron ) error_log("Tabla {$TABLA} importada ({$TReg})\n",3,'_upload.info');
}
if( $NomFile=='../tree/gs_op.unl' ){
set_time_limit(5*60);
$sql = "delete from {$_ENV['SYSDB']}gs_op";
if( $_Tron ){
error_log("SQL: Borrar gs_op\n", 3, '_upload.info');
error_log("SQL: {$sql}\n", 3, '_upload.info');
}
SS::query($sql);
$txt = file_get_contents($NomFile);
$Dim = explode("\n", $txt);
for($n=0; $n<count($Dim); $n++){
$Dim[$n] = trim($Dim[$n]);
if( $Dim[$n]!='' ){
$txt = "'".str_replace('|',"','",trim(mb_substr($Dim[$n],0,-1)))."'";
$sql = "insert into {$_ENV['SYSDB']}gs_op values ({$txt})";
if( $_Tron ) error_log("SQL: {$sql}\n",3,'_upload.info');
SS::query($sql);
}
}
if( $_Tron ) error_log("SQL: END\n",3,'_upload.info');
}else if( $NomFile=='../tree/gs_op_lng.unl' ){
set_time_limit(5*60);
$sql = "delete from {$_ENV['SYSDB']}gs_op_lng";
if( $_Tron ){
error_log("SQL: Borrar gs_op_lng\n",3,'_upload.info');
error_log("SQL: {$sql}\n",3,'_upload.info');
}
SS::query($sql);
$txt = file_get_contents($NomFile);
$Dim = explode("\n", $txt);
for($n=0; $n<count($Dim); $n++){
$Dim[$n] = trim($Dim[$n]);
if( $Dim[$n]!='' ){
$txt = "'".str_replace('|',"','",trim(mb_substr($Dim[$n],0,-1)))."'";
$sql = "insert into {$_ENV['SYSDB']}gs_op_lng values ( $txt )";
if( $_Tron ) error_log("SQL: {$sql}\n",3,'_upload.info');
SS::query($sql);
}
}
if( $_Tron ) error_log("SQL: END\n",3,'_upload.info');
}else if( $NomFile=='../tree/gs_op_ico.unl' ){
$file = 'gs_op_ico';
$TABLA = "{$_ENV['SYSDB']}gs_op_ico";
if( $_Tron ) error_log("SQL: {$TABLA}\n",3,'_upload.info');
SS::query("delete from {$TABLA}");
if( $_Tron ) error_log("FILE: ../tree/{$file}.unl\n",3,'_upload.info');
$fd = fopen( "../tree/{$file}.unl", 'r' );
while( ($txt = fgets($fd,10000)) ){
$txt =	  str_replace( '|'		 , '","'  , chop($txt) );
$txt =	  str_replace( '{&#124;}', '|'    , $txt );
$txt =	  str_replace( '{&#34;}' , '"'    , $txt );
$txt =	  str_replace( '{&#13;}' , CHR13, $txt );
$txt = '"'.str_replace( '{&#10;}' , CHR10, $txt ).'"';
$sql = "insert into {$TABLA} values ({$txt})";
if( $_Tron ) error_log("SQL: {$sql}\n",3,'_upload.info');
SS::query($sql);
}
fclose($fd);
}else if( $NomFile=='../tree/gs_tpermission.unl' ){
$file = 'gs_tpermission';
$TABLA = "{$_ENV['SYSDB']}gs_tpermission";
if( $_Tron ) error_log("SQL 2: {$TABLA}\n",3,'_upload.info');
SS::query("delete from {$TABLA}");
if( $_Tron ) error_log("FILE: ../tree/{$file}.unl\n",3,'_upload.info');
$fd = fopen("../tree/{$file}.unl", 'r');
while( ($txt = fgets($fd,10000)) ){
$txt =	   str_replace('|'		 , '","'  , chop($txt) );
$txt =	   str_replace('{&#124;}', '|'    , $txt );
$txt =	   str_replace('{&#34;}' , '"'    , $txt );
$txt =	   str_replace('{&#13;}' , CHR13, $txt );
$txt = '"'.str_replace('{&#10;}' , CHR10, $txt ).'"';
$sql = "insert into {$TABLA} values ({$txt})";
if( $_Tron ) error_log("SQL: {$sql}\n",3,'_upload.info');
SS::query($sql);
}
fclose($fd);
}else if( mb_substr($NomFile,0,8)=='../tree/' && mb_substr($NomFile,-4)=='.unl' ){
set_time_limit(5*60);
$TABLA = $_ENV['SYSDB'].mb_substr($NomFile,8,-4);
if( $_Tron ) error_log("SQL: {$TABLA}\n",3,'_upload.info');
SS::query("delete from {$TABLA}");
if( $_Tron ) error_log("FILE: ../tree/{$TABLA}.unl\n",3,'_upload.info');
$fd = fopen( "../tree/{$TABLA}.unl", 'r' );
while( ($txt = fgets($fd,10000)) ){
$txt =	   str_replace( '|'		 , '","'  , chop($txt) );
$txt =	   str_replace( '{&#124;}', '|'    , $txt );
$txt =	   str_replace( '{&#34;}' , '"'    , $txt );
$txt =	   str_replace( '{&#13;}' , CHR13, $txt );
$txt = '"'.str_replace( '{&#10;}' , CHR10, $txt ).'"';
$sql = "insert into {$TABLA} values ({$txt})";
if( $_Tron ) error_log("SQL: {$sql}\n", 3, '_upload.info');
SS::query($sql);
}
fclose($fd);
}
if( $NomFile=='../_datos/config/sql.log' ){
$CDI = trim(file_get_contents('../_datos/config/sql.cdi'));
$Dim = file('../_datos/config/sql.log');
for( $n=0; $n<count($Dim); $n++ ){
if( trim($Dim[$n])!='' ){
$oCDI = trim(mb_substr( $Dim[$n], 0, 19 ));
$txt = trim(mb_substr( $Dim[$n], 20 ));
if( $oCDI > $CDI ){
if( $_Tron ) error_log("SQL Ejecutar: {$txt}\n",3,'_upload.info');
SS::query($txt);
file_put_contents('../_datos/config/sql.cdi', $oCDI);
clearstatcache();
}
}
}
}
if( $NomFile=='../_datos/config/directory.log' ){
if( $_Tron ) error_log("Inicio actualización Directory\n",3,'_upload.info');
$CDI = trim(file_get_contents('../_datos/config/directory.cdi'));
if( $_Tron ) error_log("CDI actual: {$CDI}\n",3,'_upload.info');
$Dim = file('../_datos/config/directory.log');
for( $n=0; $n<count($Dim); $n++ ){
if( $Dim[$n]!='' ){
$oCDI = trim(mb_substr( $Dim[$n], 0, 19 ));
$txt = trim(mb_substr( $Dim[$n], 20 ));
if( $_Tron ) error_log("Comando: {$oCDI} {$txt}\n",3,'_upload.info');
if( $oCDI > $CDI ){
if( $_Tron ) error_log("Ejecutar COMANDO: {$txt}\n",3,'_upload.info');
passthru($txt);
file_put_contents('../_datos/config/directory.cdi', $oCDI);
clearstatcache();
}
}
}
}
if( $NomFile=='../_datos/config/update.log' ){
include($NomFile);
}
} while( $MacroFile!='' and !feof($fp) and ftell($fp) < $MaxFileSize );
if( $MacroFile!='' ) fclose( $fp );
if( $_Tron ) error_log("FIN\n", 3, '_upload.info');
}else if( $_GET['FILE']=='~' ){
$xUsuario = strip_tags($_POST['email']);
$ListChr = 'ABCDEFGHIJKLMNÑOPQRSTUVWXYZ0123456789ÇÜ'.
'abcdefghijklmnñopqrstuvwxyz0123456789çü'.'&.-_@';
for($i=0; $i<mb_strlen($xUsuario); $i++){
if( eSubstrCount($ListChr, mb_substr($xUsuario,$i,1))==0 ){
die('ERROR EMAIL-4');
}
}
if( $_Tron ) error_log("Ejecutar: SS::count({$_ENV['SYSDB']}gs_user, login='{$xUsuario}'\n", 3, '_upload.info');
if( SS::count("{$_ENV['SYSDB']}gs_user", "login='{$xUsuario}'")==0 ){
$Trigger = '';
}else{
$sql = "select trigger_chr from {$_ENV['SYSDB']}gs_user where login='{$xUsuario}'";
if( $_Tron ) error_log("SQL: {$sql}\n",3,'_upload.info');
SS::query($sql);
list($Trigger) = SS::get("num");
}
echo '<script type="text/javascript">top._EntrarYA("'.trim($Trigger).'");</script>';
SS::close();
if( $_HndDB ){
SS::free();
SS::close();
}
die("ok");
}
echo 'ok';
if( $_HndDB ){
SS::free();
SS::close();
}
exit;
function eFileGetVar2($Clave="", $Publicar=false){
if( !function_exists('GetValor') ){
function GetValor($Valor){
if( mb_strlen($Valor)>=2 ) if( $Valor[0]==mb_substr($Valor,-1) && ($Valor=='"' || $Valor="'") ) $Valor = mb_substr($Valor,1,-1);
if( mb_strtoupper($Valor)=='FALSE' || mb_strtoupper($Valor)=='TRUE' ) $Valor = mb_strtoupper($Valor)=='TRUE';
if( $Valor==NULL ) $Valor = "";
return $Valor;
}
}
if( !function_exists('quitaRem') ){
function quitaRem($txt){
$p = mb_strpos($txt, REM);
if( $p!==false ){
if( mb_substr($txt,$p-1,1)=="=" || mb_substr($txt,$p-2,1)=="=" || mb_substr($txt,$p-1,1)==":" ){
$p = mb_strpos($txt, REM, $p+1);
if( $p!==false ){
$txt = mb_substr($txt,0,$p-1);
}
}else{
$txt = mb_substr($txt,0,$p-1);
}
}
return $txt;
}
}
$NmFile = '../_datos/config/group.var';
$VarDentroGrupo = true;
$Variable = '';
$DimVar = array();
$RetornaDim = true;
$Valor = "";
if( eSubstrCount($Clave,'->')>0 ){
list($NmFile, $Variable) = explode('->',$Clave);
$NmFile = eScript(trim($NmFile));
$Variable = trim($Variable);
$VarDentroGrupo = false;
$Clave = $Variable;
}
if( eSubstrCount($Clave,'.')==1 ){
list($Clave, $Variable) = explode('.', $Clave);
$Clave = trim($Clave);
$Variable = trim($Variable);
$VarDentroGrupo = true;
$RetornaDim = false;
}
if( $Clave!="" ){
$Clave = mb_strtoupper(trim($Clave));
if( mb_substr($Clave,-1)!=':' ) $Clave .= ':';
}
$nv = 0;
if( eSubstrCount($NmFile,'/_datos/config/sql.ini')>0 ){
$txt = trim(@file_get_contents($NmFile));
if( mb_substr($txt,0,2)!='<'.'?' ){
$txt = gzuncompress($txt);
$Divide = ((eSubstrCount($txt,CHR10)>=eSubstrCount($txt,CHR13)) ? CHR10 : CHR13 );
$Dim = explode($Divide,$txt);
}else{
$Dim = file($NmFile);
}
}else{
$Dim = file($NmFile);
}
for($n=0; $n<count($Dim); $n++){
$Dim[$n] = quitaRem($Dim[$n]);
$Dim[$n] = trim($Dim[$n]);
if( $Dim[$n]=="" ) continue;
if( ($Clave=="" && mb_substr($Dim[$n],-1)==":") || mb_strtoupper($Dim[$n])==$Clave || !$VarDentroGrupo ){
$keyGroup = mb_substr($Dim[$n],0,-1);
if( !$VarDentroGrupo ) $n = -1;
for($i=$n+1; $i<count($Dim); $i++){
$key = quitaRem($Dim[$i]);
$key = trim($key);
if( $key!='' && $key[0]!='.' ){
if( mb_substr($key,-1)==':' ){
if( $Clave=="" ) break;
else break 2;
}
$nv++;
if( mb_substr($key,-1)==';' ) $key = trim(mb_substr($key,0,-1));
$p = mb_strpos($key,'=');
if( $p!==false ){
$NmVar = trim(mb_substr($key,0,$p));
$Valor = trim(mb_substr($key,$p+1));
if( !$VarDentroGrupo ){
$Valor = quitaRem($Valor);
$Valor = trim($Valor);
if( mb_substr($Valor,-1)==';' ) $Valor = trim(mb_substr($Valor,0,-1));
}
if( mb_strlen($Valor)>=2 ) if( $Valor[0]==mb_substr($Valor,-1) && ($Valor[0]=='"' || $Valor[0]=="'") ) $Valor = trim(mb_substr($Valor,1,-1));
if( mb_strtoupper($Valor)=='FALSE' || mb_strtoupper($Valor)=='TRUE' ) $Valor = (mb_strtoupper($Valor)=='TRUE');
if( mb_strtoupper($Valor)=='!FALSE' || mb_strtoupper($Valor)=='!TRUE' ) $Valor = (mb_strtoupper($Valor)=='!FALSE');
if( $Variable!='' ){
if( $Variable==$NmVar ) return $Valor;
}else{
if( $Clave=="" ){
$DimVar[$keyGroup][$NmVar] = $Valor;
}else{
$DimVar[$NmVar] = $Valor;
if( $Publicar ) $GLOBALS[$NmVar] = $Valor;
}
}
}
}
}
if( $Clave!="" ) break;
}
}
if( $nv>1 )
if( $RetornaDim ) return $DimVar;
return "";
}
function gsUpdateScript($Time, $File, $Op, $NewText, $De, $Desde='', $Hasta='', $Test=true){
$CDI = trim(file_get_contents('../_datos/config/update.cdi'));
if( $Time <= $CDI && $CDI!='' ) return;
$xFile = trim(file_get_contents( $File ));
switch( $Op ){
case 'S':
$xFile = $NewText . $xFile;
break;
case 'B':
if( eSubstrCount( mb_strtoupper($xFile), mb_strtoupper($De) ) > 0 ){
$i = mb_strpos( mb_strtoupper($xFile), mb_strtoupper($De) );
$xFile = mb_substr( $xFile, 0, $i ) . $NewText . mb_substr( $xFile, $i );
}
break;
case 'I':
if( eSubstrCount( mb_strtoupper($xFile), mb_strtoupper($De) ) > 0 ){
$i = mb_strpos( mb_strtoupper($xFile), mb_strtoupper($De) );
if( $Desde!='' ){
$i = mb_strpos( mb_strtoupper($xFile), mb_strtoupper($Desde), $i ) + mb_strlen($Desde);
}
if( $Hasta!='' ){
$f = mb_strpos( mb_strtoupper($xFile), mb_strtoupper($Hasta), $i );
}
$xFile = mb_substr( $xFile, 0, $i ) . $NewText . mb_substr( $xFile, $f );
}
break;
case 'A':
if( eSubstrCount( mb_strtoupper($xFile), mb_strtoupper($De) ) > 0 ){
$i = mb_strpos( mb_strtoupper($xFile), mb_strtoupper($De) ) + mb_strlen($De);
$xFile = mb_substr( $xFile, 0, $i ) . $NewText . mb_substr( $xFile, $i );
}
break;
case 'E':
$xFile .= "\n".$NewText;
break;
}
file_put_contents( $File, $xFile );
file_put_contents( '../_datos/config/update.cdi', $Time );
clearstatcache();
}
function _UnPath( $txt ){
$Dim = explode('/',str_replace('\\','/',$txt));
$Ext = explode('.',$txt);
return array( $Dim[count($Dim)-2].'/'.$Dim[count($Dim)-1], $Ext[count($Ext)-1] );
}
?>