public static $context = 0;
public static $QueryString = '';
public static $_TMP_ = 0;
public static $_x_y_z_ = '';
public static $eSubmit = '';
public static $_Connection_ = 0;
public static $SessionMaxLife = 0;
public static $_DIRWEB = '';
public static $_DIRWEB2 = '';
public static $_PathCSS = 'css';
public static $_PathIMG = 'g';
public static $_BYPHONE = false;
public static $_Platform_ = '';
public static $OS = '';
public static $_Explorer_ = '';
public static $_Resolution_ = '';
public static $_pxW_ = 0;
public static $_pxH_ = 0;
public static $_NavigatorLng_ = '';
public static $versionLocal = 0;
public static $_Path_ = '';
public static $pk_login = '';
public static $_LanguageDefault = '';
public static $_LANGUAGE_ = '';
public static $_LANGUAGE_SUFFIX = '';
public static $_Desktop = 2;
public static $_DesktopType = 0;
public static $_SessionEDF = '';
public static $UploadFile = [];
public static $commandJS = '';
public static $share = [
'file'			=> ''
,'driver'		=> ''
,'hostname'		=> ''
,'database'		=> ''
,'databaseSYS'	=> ''
,'user'			=> ''
,'password'		=> ''
,'port'			=> ''
,'transaction'	=> false
,'init'			=> []
,'pdoType'		=> ''
,'pdoConnect'	=> ''
,'isMultitenan'	=> false
,'db_path'		=> ''
];
public static $sql = [
'file'			=> ''
,'driver'		=> ''
,'hostname'		=> ''
,'database'		=> ''
,'databaseSYS'	=> ''
,'user'			=> ''
,'password'		=> ''
,'port'			=> ''
,'transaction'	=> false
,'init'			=> []
,'pdoType'		=> ''
,'pdoConnect'	=> ''
,'default'		=> ''
,'statistics'	=> false
];
public static $_SELINO = [];
public static $print_tab_public  = '';
public static $print_tab_private = '';
public static $print_public  = '';
public static $print_private = '';
public static $pdf_public = '';
public static $xls_public = '';
public static $xml_public = '';
public static $txt_public = '';
public static $csv_public = '';
public static $pdf_private = '';
public static $xls_private = '';
public static $xml_private = '';
public static $txt_private = '';
public static $csv_private = '';
public static $_notools_ = '';
public static $_LogUser_ = '';
public static $_LogHistory_ = '';
public static $_InsertToSeek = false;
public static $_InsertToSeekEdit = false;
public static $_InsertToSeekNoEdit = false;
public static $UserExport = false;
public static $_UserName = '';
public static $_UserEMail = '';
public static $_APPCODE = '';
public static $_UpdateIntervalDB = 0;
public static $_UpdateDB = 0;
public static $_LoginTime = 0;
public static $_User = -1;
public static $_Node = 0;
public static $_Tree = 0;
public static $_TreeList = '';
public static $_DT = 0;
public static $_AvisoStatus_ = '';
public static $_novedades_ = '';
public static $_CDI_ = 0;
public static $_ALERTS_ = 0;
public static $_CacheSrv = false;
public static $_CachePc = '';
public static $_DOC_ = 0;
public static $_G_ = '';
public static $_IST_ = -1;
public static $_UserLogin = '';
public static $cssSufijo = '';
public static $zoomBIG = '';
public static $zoomTLF = '';
public static $zoomSmall = '';
public static $factorZoom = 0;
public static $_logo_pdf_ = '';
public static $pk_share = 0;
public static $CHECK = [];
public static $_SP_ = '';
public static $tmp = [];
public static $var = [];
public static $_gsNomUser = '';
public static $_Development = false;
public static $_SystemUser = '';
public static $_WebMaster = '';
public static $_D_ = '';
public static $_gsACCESO = [
'TIPO'		=> ''
,'ACCESO'	=> 0
,'LOGEAR'	=> ''
,'EMAIL'	=> ''
,'iTools'	=> 0
,'Edit'		=> 0
,'DB'		=> '0'
,'Help'		=> 0
,'Shell'	=> 0
,'Cache'	=> '0'
,'Icon'		=> 0
,'Index'	=> '0'
,'Log'		=> '0'
,'Create'	=> 0
,'Main'		=> '0'
,'Patch'	=> '0'
,'Tools'	=> 0
,'Tree'		=> '0'
,'FTP'		=> '0'
,'DesEDes'	=> ''
];
public static $_L_ = [];
public static $_P_ = '';
public static $_RecentFiles = 0;
public static $_TRACE_URL_ON = false;
public static $_TRACE_URL_ = [];
public static $_gsDirAccess = [];
public static $_DEBUGSQL = false;
public static $BoxDir = '';
public static $md5ListFields = '';
public static $_Login_ = '';
public static $_Password_ = '';
public static $_Remember_ = '';
public static $_CheckCode_ = '';
public static $_Birthday_ = '';
public static $_ImgSignature_ = '';
public static $_CharSignature_ = '';
public static $_LoginTime_ = 0;
public static $encryptKey = '';
public static $_PassError_ = '';
public static $_PassTime_ = 0;
public static $VerificationMaxLife = 0;
public static $Verification = '';
public static $_VerifyCode_ = '';
public static $_VerifyCookie_ = '';
public static $_VerificationWait_ = '';